// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { TestAPI } from './test-api'
import { Test, CopyTestToTestAPI } from './test'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class TestService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TestServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private testsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.testsUrl = origin + '/api/github.com/fullstack-lang/gongreqif/go/v1/tests';
  }

  /** GET tests from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<TestAPI[]> {
    return this.getTests(GONG__StackPath, frontRepo)
  }
  getTests(GONG__StackPath: string, frontRepo: FrontRepo): Observable<TestAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<TestAPI[]>(this.testsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<TestAPI[]>('getTests', []))
      );
  }

  /** GET test by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TestAPI> {
    return this.getTest(id, GONG__StackPath, frontRepo)
  }
  getTest(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TestAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.testsUrl}/${id}`;
    return this.http.get<TestAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched test id=${id}`)),
      catchError(this.handleError<TestAPI>(`getTest id=${id}`))
    );
  }

  // postFront copy test to a version with encoded pointers and post to the back
  postFront(test: Test, GONG__StackPath: string): Observable<TestAPI> {
    let testAPI = new TestAPI
    CopyTestToTestAPI(test, testAPI)
    const id = typeof testAPI === 'number' ? testAPI : testAPI.ID
    const url = `${this.testsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<TestAPI>(url, testAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<TestAPI>('postTest'))
    );
  }
  
  /** POST: add a new test to the server */
  post(testdb: TestAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TestAPI> {
    return this.postTest(testdb, GONG__StackPath, frontRepo)
  }
  postTest(testdb: TestAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TestAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<TestAPI>(this.testsUrl, testdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted testdb id=${testdb.ID}`)
      }),
      catchError(this.handleError<TestAPI>('postTest'))
    );
  }

  /** DELETE: delete the testdb from the server */
  delete(testdb: TestAPI | number, GONG__StackPath: string): Observable<TestAPI> {
    return this.deleteTest(testdb, GONG__StackPath)
  }
  deleteTest(testdb: TestAPI | number, GONG__StackPath: string): Observable<TestAPI> {
    const id = typeof testdb === 'number' ? testdb : testdb.ID;
    const url = `${this.testsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<TestAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted testdb id=${id}`)),
      catchError(this.handleError<TestAPI>('deleteTest'))
    );
  }

  // updateFront copy test to a version with encoded pointers and update to the back
  updateFront(test: Test, GONG__StackPath: string): Observable<TestAPI> {
    let testAPI = new TestAPI
    CopyTestToTestAPI(test, testAPI)
    const id = typeof testAPI === 'number' ? testAPI : testAPI.ID
    const url = `${this.testsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<TestAPI>(url, testAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<TestAPI>('updateTest'))
    );
  }

  /** PUT: update the testdb on the server */
  update(testdb: TestAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TestAPI> {
    return this.updateTest(testdb, GONG__StackPath, frontRepo)
  }
  updateTest(testdb: TestAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TestAPI> {
    const id = typeof testdb === 'number' ? testdb : testdb.ID;
    const url = `${this.testsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<TestAPI>(url, testdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated testdb id=${testdb.ID}`)
      }),
      catchError(this.handleError<TestAPI>('updateTest'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in TestService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("TestService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
