// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongreqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Xhtml_abbr_type_sql sql.NullBool
var dummy_Xhtml_abbr_type_time time.Duration
var dummy_Xhtml_abbr_type_sort sort.Float64Slice

// Xhtml_abbr_typeAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model xhtml_abbr_typeAPI
type Xhtml_abbr_typeAPI struct {
	gorm.Model

	models.Xhtml_abbr_type_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	Xhtml_abbr_typePointersEncoding Xhtml_abbr_typePointersEncoding
}

// Xhtml_abbr_typePointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type Xhtml_abbr_typePointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// Xhtml_abbr_typeDB describes a xhtml_abbr_type in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model xhtml_abbr_typeDB
type Xhtml_abbr_typeDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field xhtml_abbr_typeDB.Name
	Name_Data sql.NullString
	
	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	Xhtml_abbr_typePointersEncoding
}

// Xhtml_abbr_typeDBs arrays xhtml_abbr_typeDBs
// swagger:response xhtml_abbr_typeDBsResponse
type Xhtml_abbr_typeDBs []Xhtml_abbr_typeDB

// Xhtml_abbr_typeDBResponse provides response
// swagger:response xhtml_abbr_typeDBResponse
type Xhtml_abbr_typeDBResponse struct {
	Xhtml_abbr_typeDB
}

// Xhtml_abbr_typeWOP is a Xhtml_abbr_type without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type Xhtml_abbr_typeWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`
	// insertion for WOP pointer fields
}

var Xhtml_abbr_type_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
}

type BackRepoXhtml_abbr_typeStruct struct {
	// stores Xhtml_abbr_typeDB according to their gorm ID
	Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB map[uint]*Xhtml_abbr_typeDB

	// stores Xhtml_abbr_typeDB ID according to Xhtml_abbr_type address
	Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID map[*models.Xhtml_abbr_type]uint

	// stores Xhtml_abbr_type according to their gorm ID
	Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr map[uint]*models.Xhtml_abbr_type

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) GetStage() (stage *models.StageStruct) {
	stage = backRepoXhtml_abbr_type.stage
	return
}

func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) GetDB() *gorm.DB {
	return backRepoXhtml_abbr_type.db
}

// GetXhtml_abbr_typeDBFromXhtml_abbr_typePtr is a handy function to access the back repo instance from the stage instance
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) GetXhtml_abbr_typeDBFromXhtml_abbr_typePtr(xhtml_abbr_type *models.Xhtml_abbr_type) (xhtml_abbr_typeDB *Xhtml_abbr_typeDB) {
	id := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID[xhtml_abbr_type]
	xhtml_abbr_typeDB = backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB[id]
	return
}

// BackRepoXhtml_abbr_type.CommitPhaseOne commits all staged instances of Xhtml_abbr_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for xhtml_abbr_type := range stage.Xhtml_abbr_types {
		backRepoXhtml_abbr_type.CommitPhaseOneInstance(xhtml_abbr_type)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, xhtml_abbr_type := range backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr {
		if _, ok := stage.Xhtml_abbr_types[xhtml_abbr_type]; !ok {
			backRepoXhtml_abbr_type.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoXhtml_abbr_type.CommitDeleteInstance commits deletion of Xhtml_abbr_type to the BackRepo
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CommitDeleteInstance(id uint) (Error error) {

	xhtml_abbr_type := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr[id]

	// xhtml_abbr_type is not staged anymore, remove xhtml_abbr_typeDB
	xhtml_abbr_typeDB := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB[id]
	query := backRepoXhtml_abbr_type.db.Unscoped().Delete(&xhtml_abbr_typeDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	delete(backRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID, xhtml_abbr_type)
	delete(backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr, id)
	delete(backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB, id)

	return
}

// BackRepoXhtml_abbr_type.CommitPhaseOneInstance commits xhtml_abbr_type staged instances of Xhtml_abbr_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CommitPhaseOneInstance(xhtml_abbr_type *models.Xhtml_abbr_type) (Error error) {

	// check if the xhtml_abbr_type is not commited yet
	if _, ok := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID[xhtml_abbr_type]; ok {
		return
	}

	// initiate xhtml_abbr_type
	var xhtml_abbr_typeDB Xhtml_abbr_typeDB
	xhtml_abbr_typeDB.CopyBasicFieldsFromXhtml_abbr_type(xhtml_abbr_type)

	query := backRepoXhtml_abbr_type.db.Create(&xhtml_abbr_typeDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	backRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID[xhtml_abbr_type] = xhtml_abbr_typeDB.ID
	backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr[xhtml_abbr_typeDB.ID] = xhtml_abbr_type
	backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB[xhtml_abbr_typeDB.ID] = &xhtml_abbr_typeDB

	return
}

// BackRepoXhtml_abbr_type.CommitPhaseTwo commits all staged instances of Xhtml_abbr_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_abbr_type := range backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr {
		backRepoXhtml_abbr_type.CommitPhaseTwoInstance(backRepo, idx, xhtml_abbr_type)
	}

	return
}

// BackRepoXhtml_abbr_type.CommitPhaseTwoInstance commits {{structname }} of models.Xhtml_abbr_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, xhtml_abbr_type *models.Xhtml_abbr_type) (Error error) {

	// fetch matching xhtml_abbr_typeDB
	if xhtml_abbr_typeDB, ok := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB[idx]; ok {

		xhtml_abbr_typeDB.CopyBasicFieldsFromXhtml_abbr_type(xhtml_abbr_type)

		// insertion point for translating pointers encodings into actual pointers
		query := backRepoXhtml_abbr_type.db.Save(&xhtml_abbr_typeDB)
		if query.Error != nil {
			log.Fatalln(query.Error)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown Xhtml_abbr_type intance %s", xhtml_abbr_type.Name))
		return err
	}

	return
}

// BackRepoXhtml_abbr_type.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CheckoutPhaseOne() (Error error) {

	xhtml_abbr_typeDBArray := make([]Xhtml_abbr_typeDB, 0)
	query := backRepoXhtml_abbr_type.db.Find(&xhtml_abbr_typeDBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	xhtml_abbr_typeInstancesToBeRemovedFromTheStage := make(map[*models.Xhtml_abbr_type]any)
	for key, value := range backRepoXhtml_abbr_type.stage.Xhtml_abbr_types {
		xhtml_abbr_typeInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, xhtml_abbr_typeDB := range xhtml_abbr_typeDBArray {
		backRepoXhtml_abbr_type.CheckoutPhaseOneInstance(&xhtml_abbr_typeDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		xhtml_abbr_type, ok := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr[xhtml_abbr_typeDB.ID]
		if ok {
			delete(xhtml_abbr_typeInstancesToBeRemovedFromTheStage, xhtml_abbr_type)
		}
	}

	// remove from stage and back repo's 3 maps all xhtml_abbr_types that are not in the checkout
	for xhtml_abbr_type := range xhtml_abbr_typeInstancesToBeRemovedFromTheStage {
		xhtml_abbr_type.Unstage(backRepoXhtml_abbr_type.GetStage())

		// remove instance from the back repo 3 maps
		xhtml_abbr_typeID := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID[xhtml_abbr_type]
		delete(backRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID, xhtml_abbr_type)
		delete(backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB, xhtml_abbr_typeID)
		delete(backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr, xhtml_abbr_typeID)
	}

	return
}

// CheckoutPhaseOneInstance takes a xhtml_abbr_typeDB that has been found in the DB, updates the backRepo and stages the
// models version of the xhtml_abbr_typeDB
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CheckoutPhaseOneInstance(xhtml_abbr_typeDB *Xhtml_abbr_typeDB) (Error error) {

	xhtml_abbr_type, ok := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr[xhtml_abbr_typeDB.ID]
	if !ok {
		xhtml_abbr_type = new(models.Xhtml_abbr_type)

		backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr[xhtml_abbr_typeDB.ID] = xhtml_abbr_type
		backRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID[xhtml_abbr_type] = xhtml_abbr_typeDB.ID

		// append model store with the new element
		xhtml_abbr_type.Name = xhtml_abbr_typeDB.Name_Data.String
		xhtml_abbr_type.Stage(backRepoXhtml_abbr_type.GetStage())
	}
	xhtml_abbr_typeDB.CopyBasicFieldsToXhtml_abbr_type(xhtml_abbr_type)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	xhtml_abbr_type.Stage(backRepoXhtml_abbr_type.GetStage())

	// preserve pointer to xhtml_abbr_typeDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB)[xhtml_abbr_typeDB hold variable pointers
	xhtml_abbr_typeDB_Data := *xhtml_abbr_typeDB
	preservedPtrToXhtml_abbr_type := &xhtml_abbr_typeDB_Data
	backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB[xhtml_abbr_typeDB.ID] = preservedPtrToXhtml_abbr_type

	return
}

// BackRepoXhtml_abbr_type.CheckoutPhaseTwo Checkouts all staged instances of Xhtml_abbr_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, xhtml_abbr_typeDB := range backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB {
		backRepoXhtml_abbr_type.CheckoutPhaseTwoInstance(backRepo, xhtml_abbr_typeDB)
	}
	return
}

// BackRepoXhtml_abbr_type.CheckoutPhaseTwoInstance Checkouts staged instances of Xhtml_abbr_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, xhtml_abbr_typeDB *Xhtml_abbr_typeDB) (Error error) {

	xhtml_abbr_type := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr[xhtml_abbr_typeDB.ID]

	xhtml_abbr_typeDB.DecodePointers(backRepo, xhtml_abbr_type)

	return
}

func (xhtml_abbr_typeDB *Xhtml_abbr_typeDB) DecodePointers(backRepo *BackRepoStruct, xhtml_abbr_type *models.Xhtml_abbr_type) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitXhtml_abbr_type allows commit of a single xhtml_abbr_type (if already staged)
func (backRepo *BackRepoStruct) CommitXhtml_abbr_type(xhtml_abbr_type *models.Xhtml_abbr_type) {
	backRepo.BackRepoXhtml_abbr_type.CommitPhaseOneInstance(xhtml_abbr_type)
	if id, ok := backRepo.BackRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID[xhtml_abbr_type]; ok {
		backRepo.BackRepoXhtml_abbr_type.CommitPhaseTwoInstance(backRepo, id, xhtml_abbr_type)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitXhtml_abbr_type allows checkout of a single xhtml_abbr_type (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutXhtml_abbr_type(xhtml_abbr_type *models.Xhtml_abbr_type) {
	// check if the xhtml_abbr_type is staged
	if _, ok := backRepo.BackRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID[xhtml_abbr_type]; ok {

		if id, ok := backRepo.BackRepoXhtml_abbr_type.Map_Xhtml_abbr_typePtr_Xhtml_abbr_typeDBID[xhtml_abbr_type]; ok {
			var xhtml_abbr_typeDB Xhtml_abbr_typeDB
			xhtml_abbr_typeDB.ID = id

			if err := backRepo.BackRepoXhtml_abbr_type.db.First(&xhtml_abbr_typeDB, id).Error; err != nil {
				log.Fatalln("CheckoutXhtml_abbr_type : Problem with getting object with id:", id)
			}
			backRepo.BackRepoXhtml_abbr_type.CheckoutPhaseOneInstance(&xhtml_abbr_typeDB)
			backRepo.BackRepoXhtml_abbr_type.CheckoutPhaseTwoInstance(backRepo, &xhtml_abbr_typeDB)
		}
	}
}

// CopyBasicFieldsFromXhtml_abbr_type
func (xhtml_abbr_typeDB *Xhtml_abbr_typeDB) CopyBasicFieldsFromXhtml_abbr_type(xhtml_abbr_type *models.Xhtml_abbr_type) {
	// insertion point for fields commit

	xhtml_abbr_typeDB.Name_Data.String = xhtml_abbr_type.Name
	xhtml_abbr_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_abbr_type_WOP
func (xhtml_abbr_typeDB *Xhtml_abbr_typeDB) CopyBasicFieldsFromXhtml_abbr_type_WOP(xhtml_abbr_type *models.Xhtml_abbr_type_WOP) {
	// insertion point for fields commit

	xhtml_abbr_typeDB.Name_Data.String = xhtml_abbr_type.Name
	xhtml_abbr_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_abbr_typeWOP
func (xhtml_abbr_typeDB *Xhtml_abbr_typeDB) CopyBasicFieldsFromXhtml_abbr_typeWOP(xhtml_abbr_type *Xhtml_abbr_typeWOP) {
	// insertion point for fields commit

	xhtml_abbr_typeDB.Name_Data.String = xhtml_abbr_type.Name
	xhtml_abbr_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsToXhtml_abbr_type
func (xhtml_abbr_typeDB *Xhtml_abbr_typeDB) CopyBasicFieldsToXhtml_abbr_type(xhtml_abbr_type *models.Xhtml_abbr_type) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_abbr_type.Name = xhtml_abbr_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_abbr_type_WOP
func (xhtml_abbr_typeDB *Xhtml_abbr_typeDB) CopyBasicFieldsToXhtml_abbr_type_WOP(xhtml_abbr_type *models.Xhtml_abbr_type_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_abbr_type.Name = xhtml_abbr_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_abbr_typeWOP
func (xhtml_abbr_typeDB *Xhtml_abbr_typeDB) CopyBasicFieldsToXhtml_abbr_typeWOP(xhtml_abbr_type *Xhtml_abbr_typeWOP) {
	xhtml_abbr_type.ID = int(xhtml_abbr_typeDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_abbr_type.Name = xhtml_abbr_typeDB.Name_Data.String
}

// Backup generates a json file from a slice of all Xhtml_abbr_typeDB instances in the backrepo
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "Xhtml_abbr_typeDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_abbr_typeDB, 0)
	for _, xhtml_abbr_typeDB := range backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB {
		forBackup = append(forBackup, xhtml_abbr_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json Xhtml_abbr_type ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json Xhtml_abbr_type file", err.Error())
	}
}

// Backup generates a json file from a slice of all Xhtml_abbr_typeDB instances in the backrepo
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_abbr_typeDB, 0)
	for _, xhtml_abbr_typeDB := range backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB {
		forBackup = append(forBackup, xhtml_abbr_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Xhtml_abbr_type")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Xhtml_abbr_type_Fields, -1)
	for _, xhtml_abbr_typeDB := range forBackup {

		var xhtml_abbr_typeWOP Xhtml_abbr_typeWOP
		xhtml_abbr_typeDB.CopyBasicFieldsToXhtml_abbr_typeWOP(&xhtml_abbr_typeWOP)

		row := sh.AddRow()
		row.WriteStruct(&xhtml_abbr_typeWOP, -1)
	}
}

// RestoreXL from the "Xhtml_abbr_type" sheet all Xhtml_abbr_typeDB instances
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoXhtml_abbr_typeid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Xhtml_abbr_type"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoXhtml_abbr_type.rowVisitorXhtml_abbr_type)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) rowVisitorXhtml_abbr_type(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var xhtml_abbr_typeWOP Xhtml_abbr_typeWOP
		row.ReadStruct(&xhtml_abbr_typeWOP)

		// add the unmarshalled struct to the stage
		xhtml_abbr_typeDB := new(Xhtml_abbr_typeDB)
		xhtml_abbr_typeDB.CopyBasicFieldsFromXhtml_abbr_typeWOP(&xhtml_abbr_typeWOP)

		xhtml_abbr_typeDB_ID_atBackupTime := xhtml_abbr_typeDB.ID
		xhtml_abbr_typeDB.ID = 0
		query := backRepoXhtml_abbr_type.db.Create(xhtml_abbr_typeDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB[xhtml_abbr_typeDB.ID] = xhtml_abbr_typeDB
		BackRepoXhtml_abbr_typeid_atBckpTime_newID[xhtml_abbr_typeDB_ID_atBackupTime] = xhtml_abbr_typeDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "Xhtml_abbr_typeDB.json" in dirPath that stores an array
// of Xhtml_abbr_typeDB and stores it in the database
// the map BackRepoXhtml_abbr_typeid_atBckpTime_newID is updated accordingly
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoXhtml_abbr_typeid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "Xhtml_abbr_typeDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json Xhtml_abbr_type file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*Xhtml_abbr_typeDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB
	for _, xhtml_abbr_typeDB := range forRestore {

		xhtml_abbr_typeDB_ID_atBackupTime := xhtml_abbr_typeDB.ID
		xhtml_abbr_typeDB.ID = 0
		query := backRepoXhtml_abbr_type.db.Create(xhtml_abbr_typeDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB[xhtml_abbr_typeDB.ID] = xhtml_abbr_typeDB
		BackRepoXhtml_abbr_typeid_atBckpTime_newID[xhtml_abbr_typeDB_ID_atBackupTime] = xhtml_abbr_typeDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json Xhtml_abbr_type file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Xhtml_abbr_type>id_atBckpTime_newID
// to compute new index
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) RestorePhaseTwo() {

	for _, xhtml_abbr_typeDB := range backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB {

		// next line of code is to avert unused variable compilation error
		_ = xhtml_abbr_typeDB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		query := backRepoXhtml_abbr_type.db.Model(xhtml_abbr_typeDB).Updates(*xhtml_abbr_typeDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
	}

}

// BackRepoXhtml_abbr_type.ResetReversePointers commits all staged instances of Xhtml_abbr_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_abbr_type := range backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typePtr {
		backRepoXhtml_abbr_type.ResetReversePointersInstance(backRepo, idx, xhtml_abbr_type)
	}

	return
}

func (backRepoXhtml_abbr_type *BackRepoXhtml_abbr_typeStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, xhtml_abbr_type *models.Xhtml_abbr_type) (Error error) {

	// fetch matching xhtml_abbr_typeDB
	if xhtml_abbr_typeDB, ok := backRepoXhtml_abbr_type.Map_Xhtml_abbr_typeDBID_Xhtml_abbr_typeDB[idx]; ok {
		_ = xhtml_abbr_typeDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoXhtml_abbr_typeid_atBckpTime_newID map[uint]uint
