// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongreqif/go/db"
	"github.com/fullstack-lang/gongreqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Xhtml_pre_type_sql sql.NullBool
var dummy_Xhtml_pre_type_time time.Duration
var dummy_Xhtml_pre_type_sort sort.Float64Slice

// Xhtml_pre_typeAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model xhtml_pre_typeAPI
type Xhtml_pre_typeAPI struct {
	gorm.Model

	models.Xhtml_pre_type_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	Xhtml_pre_typePointersEncoding Xhtml_pre_typePointersEncoding
}

// Xhtml_pre_typePointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type Xhtml_pre_typePointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// Xhtml_pre_typeDB describes a xhtml_pre_type in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model xhtml_pre_typeDB
type Xhtml_pre_typeDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field xhtml_pre_typeDB.Name
	Name_Data sql.NullString

	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	Xhtml_pre_typePointersEncoding
}

// Xhtml_pre_typeDBs arrays xhtml_pre_typeDBs
// swagger:response xhtml_pre_typeDBsResponse
type Xhtml_pre_typeDBs []Xhtml_pre_typeDB

// Xhtml_pre_typeDBResponse provides response
// swagger:response xhtml_pre_typeDBResponse
type Xhtml_pre_typeDBResponse struct {
	Xhtml_pre_typeDB
}

// Xhtml_pre_typeWOP is a Xhtml_pre_type without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type Xhtml_pre_typeWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`
	// insertion for WOP pointer fields
}

var Xhtml_pre_type_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
}

type BackRepoXhtml_pre_typeStruct struct {
	// stores Xhtml_pre_typeDB according to their gorm ID
	Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB map[uint]*Xhtml_pre_typeDB

	// stores Xhtml_pre_typeDB ID according to Xhtml_pre_type address
	Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID map[*models.Xhtml_pre_type]uint

	// stores Xhtml_pre_type according to their gorm ID
	Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr map[uint]*models.Xhtml_pre_type

	db db.DBInterface

	stage *models.Stage
}

func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) GetStage() (stage *models.Stage) {
	stage = backRepoXhtml_pre_type.stage
	return
}

func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) GetDB() db.DBInterface {
	return backRepoXhtml_pre_type.db
}

// GetXhtml_pre_typeDBFromXhtml_pre_typePtr is a handy function to access the back repo instance from the stage instance
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) GetXhtml_pre_typeDBFromXhtml_pre_typePtr(xhtml_pre_type *models.Xhtml_pre_type) (xhtml_pre_typeDB *Xhtml_pre_typeDB) {
	id := backRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID[xhtml_pre_type]
	xhtml_pre_typeDB = backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB[id]
	return
}

// BackRepoXhtml_pre_type.CommitPhaseOne commits all staged instances of Xhtml_pre_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CommitPhaseOne(stage *models.Stage) (Error error) {

	var xhtml_pre_types []*models.Xhtml_pre_type
	for xhtml_pre_type := range stage.Xhtml_pre_types {
		xhtml_pre_types = append(xhtml_pre_types, xhtml_pre_type)
	}

	// Sort by the order stored in Map_Staged_Order.
	sort.Slice(xhtml_pre_types, func(i, j int) bool {
		return stage.Xhtml_pre_typeMap_Staged_Order[xhtml_pre_types[i]] < stage.Xhtml_pre_typeMap_Staged_Order[xhtml_pre_types[j]]
	})

	for _, xhtml_pre_type := range xhtml_pre_types {
		backRepoXhtml_pre_type.CommitPhaseOneInstance(xhtml_pre_type)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, xhtml_pre_type := range backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr {
		if _, ok := stage.Xhtml_pre_types[xhtml_pre_type]; !ok {
			backRepoXhtml_pre_type.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoXhtml_pre_type.CommitDeleteInstance commits deletion of Xhtml_pre_type to the BackRepo
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CommitDeleteInstance(id uint) (Error error) {

	xhtml_pre_type := backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr[id]

	// xhtml_pre_type is not staged anymore, remove xhtml_pre_typeDB
	xhtml_pre_typeDB := backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB[id]
	db, _ := backRepoXhtml_pre_type.db.Unscoped()
	_, err := db.Delete(xhtml_pre_typeDB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	delete(backRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID, xhtml_pre_type)
	delete(backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr, id)
	delete(backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB, id)

	return
}

// BackRepoXhtml_pre_type.CommitPhaseOneInstance commits xhtml_pre_type staged instances of Xhtml_pre_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CommitPhaseOneInstance(xhtml_pre_type *models.Xhtml_pre_type) (Error error) {

	// check if the xhtml_pre_type is not commited yet
	if _, ok := backRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID[xhtml_pre_type]; ok {
		return
	}

	// initiate xhtml_pre_type
	var xhtml_pre_typeDB Xhtml_pre_typeDB
	xhtml_pre_typeDB.CopyBasicFieldsFromXhtml_pre_type(xhtml_pre_type)

	_, err := backRepoXhtml_pre_type.db.Create(&xhtml_pre_typeDB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	backRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID[xhtml_pre_type] = xhtml_pre_typeDB.ID
	backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr[xhtml_pre_typeDB.ID] = xhtml_pre_type
	backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB[xhtml_pre_typeDB.ID] = &xhtml_pre_typeDB

	return
}

// BackRepoXhtml_pre_type.CommitPhaseTwo commits all staged instances of Xhtml_pre_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_pre_type := range backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr {
		backRepoXhtml_pre_type.CommitPhaseTwoInstance(backRepo, idx, xhtml_pre_type)
	}

	return
}

// BackRepoXhtml_pre_type.CommitPhaseTwoInstance commits {{structname }} of models.Xhtml_pre_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, xhtml_pre_type *models.Xhtml_pre_type) (Error error) {

	// fetch matching xhtml_pre_typeDB
	if xhtml_pre_typeDB, ok := backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB[idx]; ok {

		xhtml_pre_typeDB.CopyBasicFieldsFromXhtml_pre_type(xhtml_pre_type)

		// insertion point for translating pointers encodings into actual pointers
		_, err := backRepoXhtml_pre_type.db.Save(xhtml_pre_typeDB)
		if err != nil {
			log.Fatal(err)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown Xhtml_pre_type intance %s", xhtml_pre_type.Name))
		return err
	}

	return
}

// BackRepoXhtml_pre_type.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CheckoutPhaseOne() (Error error) {

	xhtml_pre_typeDBArray := make([]Xhtml_pre_typeDB, 0)
	_, err := backRepoXhtml_pre_type.db.Find(&xhtml_pre_typeDBArray)
	if err != nil {
		return err
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	xhtml_pre_typeInstancesToBeRemovedFromTheStage := make(map[*models.Xhtml_pre_type]any)
	for key, value := range backRepoXhtml_pre_type.stage.Xhtml_pre_types {
		xhtml_pre_typeInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, xhtml_pre_typeDB := range xhtml_pre_typeDBArray {
		backRepoXhtml_pre_type.CheckoutPhaseOneInstance(&xhtml_pre_typeDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		xhtml_pre_type, ok := backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr[xhtml_pre_typeDB.ID]
		if ok {
			delete(xhtml_pre_typeInstancesToBeRemovedFromTheStage, xhtml_pre_type)
		}
	}

	// remove from stage and back repo's 3 maps all xhtml_pre_types that are not in the checkout
	for xhtml_pre_type := range xhtml_pre_typeInstancesToBeRemovedFromTheStage {
		xhtml_pre_type.Unstage(backRepoXhtml_pre_type.GetStage())

		// remove instance from the back repo 3 maps
		xhtml_pre_typeID := backRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID[xhtml_pre_type]
		delete(backRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID, xhtml_pre_type)
		delete(backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB, xhtml_pre_typeID)
		delete(backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr, xhtml_pre_typeID)
	}

	return
}

// CheckoutPhaseOneInstance takes a xhtml_pre_typeDB that has been found in the DB, updates the backRepo and stages the
// models version of the xhtml_pre_typeDB
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CheckoutPhaseOneInstance(xhtml_pre_typeDB *Xhtml_pre_typeDB) (Error error) {

	xhtml_pre_type, ok := backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr[xhtml_pre_typeDB.ID]
	if !ok {
		xhtml_pre_type = new(models.Xhtml_pre_type)

		backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr[xhtml_pre_typeDB.ID] = xhtml_pre_type
		backRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID[xhtml_pre_type] = xhtml_pre_typeDB.ID

		// append model store with the new element
		xhtml_pre_type.Name = xhtml_pre_typeDB.Name_Data.String
		xhtml_pre_type.Stage(backRepoXhtml_pre_type.GetStage())
	}
	xhtml_pre_typeDB.CopyBasicFieldsToXhtml_pre_type(xhtml_pre_type)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	xhtml_pre_type.Stage(backRepoXhtml_pre_type.GetStage())

	// preserve pointer to xhtml_pre_typeDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB)[xhtml_pre_typeDB hold variable pointers
	xhtml_pre_typeDB_Data := *xhtml_pre_typeDB
	preservedPtrToXhtml_pre_type := &xhtml_pre_typeDB_Data
	backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB[xhtml_pre_typeDB.ID] = preservedPtrToXhtml_pre_type

	return
}

// BackRepoXhtml_pre_type.CheckoutPhaseTwo Checkouts all staged instances of Xhtml_pre_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, xhtml_pre_typeDB := range backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB {
		backRepoXhtml_pre_type.CheckoutPhaseTwoInstance(backRepo, xhtml_pre_typeDB)
	}
	return
}

// BackRepoXhtml_pre_type.CheckoutPhaseTwoInstance Checkouts staged instances of Xhtml_pre_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, xhtml_pre_typeDB *Xhtml_pre_typeDB) (Error error) {

	xhtml_pre_type := backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr[xhtml_pre_typeDB.ID]

	xhtml_pre_typeDB.DecodePointers(backRepo, xhtml_pre_type)

	return
}

func (xhtml_pre_typeDB *Xhtml_pre_typeDB) DecodePointers(backRepo *BackRepoStruct, xhtml_pre_type *models.Xhtml_pre_type) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitXhtml_pre_type allows commit of a single xhtml_pre_type (if already staged)
func (backRepo *BackRepoStruct) CommitXhtml_pre_type(xhtml_pre_type *models.Xhtml_pre_type) {
	backRepo.BackRepoXhtml_pre_type.CommitPhaseOneInstance(xhtml_pre_type)
	if id, ok := backRepo.BackRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID[xhtml_pre_type]; ok {
		backRepo.BackRepoXhtml_pre_type.CommitPhaseTwoInstance(backRepo, id, xhtml_pre_type)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitXhtml_pre_type allows checkout of a single xhtml_pre_type (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutXhtml_pre_type(xhtml_pre_type *models.Xhtml_pre_type) {
	// check if the xhtml_pre_type is staged
	if _, ok := backRepo.BackRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID[xhtml_pre_type]; ok {

		if id, ok := backRepo.BackRepoXhtml_pre_type.Map_Xhtml_pre_typePtr_Xhtml_pre_typeDBID[xhtml_pre_type]; ok {
			var xhtml_pre_typeDB Xhtml_pre_typeDB
			xhtml_pre_typeDB.ID = id

			if _, err := backRepo.BackRepoXhtml_pre_type.db.First(&xhtml_pre_typeDB, id); err != nil {
				log.Fatalln("CheckoutXhtml_pre_type : Problem with getting object with id:", id)
			}
			backRepo.BackRepoXhtml_pre_type.CheckoutPhaseOneInstance(&xhtml_pre_typeDB)
			backRepo.BackRepoXhtml_pre_type.CheckoutPhaseTwoInstance(backRepo, &xhtml_pre_typeDB)
		}
	}
}

// CopyBasicFieldsFromXhtml_pre_type
func (xhtml_pre_typeDB *Xhtml_pre_typeDB) CopyBasicFieldsFromXhtml_pre_type(xhtml_pre_type *models.Xhtml_pre_type) {
	// insertion point for fields commit

	xhtml_pre_typeDB.Name_Data.String = xhtml_pre_type.Name
	xhtml_pre_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_pre_type_WOP
func (xhtml_pre_typeDB *Xhtml_pre_typeDB) CopyBasicFieldsFromXhtml_pre_type_WOP(xhtml_pre_type *models.Xhtml_pre_type_WOP) {
	// insertion point for fields commit

	xhtml_pre_typeDB.Name_Data.String = xhtml_pre_type.Name
	xhtml_pre_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_pre_typeWOP
func (xhtml_pre_typeDB *Xhtml_pre_typeDB) CopyBasicFieldsFromXhtml_pre_typeWOP(xhtml_pre_type *Xhtml_pre_typeWOP) {
	// insertion point for fields commit

	xhtml_pre_typeDB.Name_Data.String = xhtml_pre_type.Name
	xhtml_pre_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsToXhtml_pre_type
func (xhtml_pre_typeDB *Xhtml_pre_typeDB) CopyBasicFieldsToXhtml_pre_type(xhtml_pre_type *models.Xhtml_pre_type) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_pre_type.Name = xhtml_pre_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_pre_type_WOP
func (xhtml_pre_typeDB *Xhtml_pre_typeDB) CopyBasicFieldsToXhtml_pre_type_WOP(xhtml_pre_type *models.Xhtml_pre_type_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_pre_type.Name = xhtml_pre_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_pre_typeWOP
func (xhtml_pre_typeDB *Xhtml_pre_typeDB) CopyBasicFieldsToXhtml_pre_typeWOP(xhtml_pre_type *Xhtml_pre_typeWOP) {
	xhtml_pre_type.ID = int(xhtml_pre_typeDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_pre_type.Name = xhtml_pre_typeDB.Name_Data.String
}

// Backup generates a json file from a slice of all Xhtml_pre_typeDB instances in the backrepo
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "Xhtml_pre_typeDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_pre_typeDB, 0)
	for _, xhtml_pre_typeDB := range backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB {
		forBackup = append(forBackup, xhtml_pre_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json Xhtml_pre_type ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json Xhtml_pre_type file", err.Error())
	}
}

// Backup generates a json file from a slice of all Xhtml_pre_typeDB instances in the backrepo
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_pre_typeDB, 0)
	for _, xhtml_pre_typeDB := range backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB {
		forBackup = append(forBackup, xhtml_pre_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Xhtml_pre_type")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Xhtml_pre_type_Fields, -1)
	for _, xhtml_pre_typeDB := range forBackup {

		var xhtml_pre_typeWOP Xhtml_pre_typeWOP
		xhtml_pre_typeDB.CopyBasicFieldsToXhtml_pre_typeWOP(&xhtml_pre_typeWOP)

		row := sh.AddRow()
		row.WriteStruct(&xhtml_pre_typeWOP, -1)
	}
}

// RestoreXL from the "Xhtml_pre_type" sheet all Xhtml_pre_typeDB instances
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoXhtml_pre_typeid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Xhtml_pre_type"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoXhtml_pre_type.rowVisitorXhtml_pre_type)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) rowVisitorXhtml_pre_type(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var xhtml_pre_typeWOP Xhtml_pre_typeWOP
		row.ReadStruct(&xhtml_pre_typeWOP)

		// add the unmarshalled struct to the stage
		xhtml_pre_typeDB := new(Xhtml_pre_typeDB)
		xhtml_pre_typeDB.CopyBasicFieldsFromXhtml_pre_typeWOP(&xhtml_pre_typeWOP)

		xhtml_pre_typeDB_ID_atBackupTime := xhtml_pre_typeDB.ID
		xhtml_pre_typeDB.ID = 0
		_, err := backRepoXhtml_pre_type.db.Create(xhtml_pre_typeDB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB[xhtml_pre_typeDB.ID] = xhtml_pre_typeDB
		BackRepoXhtml_pre_typeid_atBckpTime_newID[xhtml_pre_typeDB_ID_atBackupTime] = xhtml_pre_typeDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "Xhtml_pre_typeDB.json" in dirPath that stores an array
// of Xhtml_pre_typeDB and stores it in the database
// the map BackRepoXhtml_pre_typeid_atBckpTime_newID is updated accordingly
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoXhtml_pre_typeid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "Xhtml_pre_typeDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json Xhtml_pre_type file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*Xhtml_pre_typeDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB
	for _, xhtml_pre_typeDB := range forRestore {

		xhtml_pre_typeDB_ID_atBackupTime := xhtml_pre_typeDB.ID
		xhtml_pre_typeDB.ID = 0
		_, err := backRepoXhtml_pre_type.db.Create(xhtml_pre_typeDB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB[xhtml_pre_typeDB.ID] = xhtml_pre_typeDB
		BackRepoXhtml_pre_typeid_atBckpTime_newID[xhtml_pre_typeDB_ID_atBackupTime] = xhtml_pre_typeDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json Xhtml_pre_type file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Xhtml_pre_type>id_atBckpTime_newID
// to compute new index
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) RestorePhaseTwo() {

	for _, xhtml_pre_typeDB := range backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB {

		// next line of code is to avert unused variable compilation error
		_ = xhtml_pre_typeDB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		db, _ := backRepoXhtml_pre_type.db.Model(xhtml_pre_typeDB)
		_, err := db.Updates(*xhtml_pre_typeDB)
		if err != nil {
			log.Fatal(err)
		}
	}

}

// BackRepoXhtml_pre_type.ResetReversePointers commits all staged instances of Xhtml_pre_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_pre_type := range backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typePtr {
		backRepoXhtml_pre_type.ResetReversePointersInstance(backRepo, idx, xhtml_pre_type)
	}

	return
}

func (backRepoXhtml_pre_type *BackRepoXhtml_pre_typeStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, xhtml_pre_type *models.Xhtml_pre_type) (Error error) {

	// fetch matching xhtml_pre_typeDB
	if xhtml_pre_typeDB, ok := backRepoXhtml_pre_type.Map_Xhtml_pre_typeDBID_Xhtml_pre_typeDB[idx]; ok {
		_ = xhtml_pre_typeDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoXhtml_pre_typeid_atBckpTime_newID map[uint]uint
