// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongreqif/go/db"
	"github.com/fullstack-lang/gongreqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Xhtml_ul_type_sql sql.NullBool
var dummy_Xhtml_ul_type_time time.Duration
var dummy_Xhtml_ul_type_sort sort.Float64Slice

// Xhtml_ul_typeAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model xhtml_ul_typeAPI
type Xhtml_ul_typeAPI struct {
	gorm.Model

	models.Xhtml_ul_type_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	Xhtml_ul_typePointersEncoding Xhtml_ul_typePointersEncoding
}

// Xhtml_ul_typePointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type Xhtml_ul_typePointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// Xhtml_ul_typeDB describes a xhtml_ul_type in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model xhtml_ul_typeDB
type Xhtml_ul_typeDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field xhtml_ul_typeDB.Name
	Name_Data sql.NullString

	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	Xhtml_ul_typePointersEncoding
}

// Xhtml_ul_typeDBs arrays xhtml_ul_typeDBs
// swagger:response xhtml_ul_typeDBsResponse
type Xhtml_ul_typeDBs []Xhtml_ul_typeDB

// Xhtml_ul_typeDBResponse provides response
// swagger:response xhtml_ul_typeDBResponse
type Xhtml_ul_typeDBResponse struct {
	Xhtml_ul_typeDB
}

// Xhtml_ul_typeWOP is a Xhtml_ul_type without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type Xhtml_ul_typeWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`
	// insertion for WOP pointer fields
}

var Xhtml_ul_type_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
}

type BackRepoXhtml_ul_typeStruct struct {
	// stores Xhtml_ul_typeDB according to their gorm ID
	Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB map[uint]*Xhtml_ul_typeDB

	// stores Xhtml_ul_typeDB ID according to Xhtml_ul_type address
	Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID map[*models.Xhtml_ul_type]uint

	// stores Xhtml_ul_type according to their gorm ID
	Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr map[uint]*models.Xhtml_ul_type

	db db.DBInterface

	stage *models.Stage
}

func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) GetStage() (stage *models.Stage) {
	stage = backRepoXhtml_ul_type.stage
	return
}

func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) GetDB() db.DBInterface {
	return backRepoXhtml_ul_type.db
}

// GetXhtml_ul_typeDBFromXhtml_ul_typePtr is a handy function to access the back repo instance from the stage instance
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) GetXhtml_ul_typeDBFromXhtml_ul_typePtr(xhtml_ul_type *models.Xhtml_ul_type) (xhtml_ul_typeDB *Xhtml_ul_typeDB) {
	id := backRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID[xhtml_ul_type]
	xhtml_ul_typeDB = backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB[id]
	return
}

// BackRepoXhtml_ul_type.CommitPhaseOne commits all staged instances of Xhtml_ul_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CommitPhaseOne(stage *models.Stage) (Error error) {

	var xhtml_ul_types []*models.Xhtml_ul_type
	for xhtml_ul_type := range stage.Xhtml_ul_types {
		xhtml_ul_types = append(xhtml_ul_types, xhtml_ul_type)
	}

	// Sort by the order stored in Map_Staged_Order.
	sort.Slice(xhtml_ul_types, func(i, j int) bool {
		return stage.Xhtml_ul_typeMap_Staged_Order[xhtml_ul_types[i]] < stage.Xhtml_ul_typeMap_Staged_Order[xhtml_ul_types[j]]
	})

	for _, xhtml_ul_type := range xhtml_ul_types {
		backRepoXhtml_ul_type.CommitPhaseOneInstance(xhtml_ul_type)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, xhtml_ul_type := range backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr {
		if _, ok := stage.Xhtml_ul_types[xhtml_ul_type]; !ok {
			backRepoXhtml_ul_type.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoXhtml_ul_type.CommitDeleteInstance commits deletion of Xhtml_ul_type to the BackRepo
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CommitDeleteInstance(id uint) (Error error) {

	xhtml_ul_type := backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr[id]

	// xhtml_ul_type is not staged anymore, remove xhtml_ul_typeDB
	xhtml_ul_typeDB := backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB[id]
	db, _ := backRepoXhtml_ul_type.db.Unscoped()
	_, err := db.Delete(xhtml_ul_typeDB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	delete(backRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID, xhtml_ul_type)
	delete(backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr, id)
	delete(backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB, id)

	return
}

// BackRepoXhtml_ul_type.CommitPhaseOneInstance commits xhtml_ul_type staged instances of Xhtml_ul_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CommitPhaseOneInstance(xhtml_ul_type *models.Xhtml_ul_type) (Error error) {

	// check if the xhtml_ul_type is not commited yet
	if _, ok := backRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID[xhtml_ul_type]; ok {
		return
	}

	// initiate xhtml_ul_type
	var xhtml_ul_typeDB Xhtml_ul_typeDB
	xhtml_ul_typeDB.CopyBasicFieldsFromXhtml_ul_type(xhtml_ul_type)

	_, err := backRepoXhtml_ul_type.db.Create(&xhtml_ul_typeDB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	backRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID[xhtml_ul_type] = xhtml_ul_typeDB.ID
	backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr[xhtml_ul_typeDB.ID] = xhtml_ul_type
	backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB[xhtml_ul_typeDB.ID] = &xhtml_ul_typeDB

	return
}

// BackRepoXhtml_ul_type.CommitPhaseTwo commits all staged instances of Xhtml_ul_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_ul_type := range backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr {
		backRepoXhtml_ul_type.CommitPhaseTwoInstance(backRepo, idx, xhtml_ul_type)
	}

	return
}

// BackRepoXhtml_ul_type.CommitPhaseTwoInstance commits {{structname }} of models.Xhtml_ul_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, xhtml_ul_type *models.Xhtml_ul_type) (Error error) {

	// fetch matching xhtml_ul_typeDB
	if xhtml_ul_typeDB, ok := backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB[idx]; ok {

		xhtml_ul_typeDB.CopyBasicFieldsFromXhtml_ul_type(xhtml_ul_type)

		// insertion point for translating pointers encodings into actual pointers
		_, err := backRepoXhtml_ul_type.db.Save(xhtml_ul_typeDB)
		if err != nil {
			log.Fatal(err)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown Xhtml_ul_type intance %s", xhtml_ul_type.Name))
		return err
	}

	return
}

// BackRepoXhtml_ul_type.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CheckoutPhaseOne() (Error error) {

	xhtml_ul_typeDBArray := make([]Xhtml_ul_typeDB, 0)
	_, err := backRepoXhtml_ul_type.db.Find(&xhtml_ul_typeDBArray)
	if err != nil {
		return err
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	xhtml_ul_typeInstancesToBeRemovedFromTheStage := make(map[*models.Xhtml_ul_type]any)
	for key, value := range backRepoXhtml_ul_type.stage.Xhtml_ul_types {
		xhtml_ul_typeInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, xhtml_ul_typeDB := range xhtml_ul_typeDBArray {
		backRepoXhtml_ul_type.CheckoutPhaseOneInstance(&xhtml_ul_typeDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		xhtml_ul_type, ok := backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr[xhtml_ul_typeDB.ID]
		if ok {
			delete(xhtml_ul_typeInstancesToBeRemovedFromTheStage, xhtml_ul_type)
		}
	}

	// remove from stage and back repo's 3 maps all xhtml_ul_types that are not in the checkout
	for xhtml_ul_type := range xhtml_ul_typeInstancesToBeRemovedFromTheStage {
		xhtml_ul_type.Unstage(backRepoXhtml_ul_type.GetStage())

		// remove instance from the back repo 3 maps
		xhtml_ul_typeID := backRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID[xhtml_ul_type]
		delete(backRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID, xhtml_ul_type)
		delete(backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB, xhtml_ul_typeID)
		delete(backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr, xhtml_ul_typeID)
	}

	return
}

// CheckoutPhaseOneInstance takes a xhtml_ul_typeDB that has been found in the DB, updates the backRepo and stages the
// models version of the xhtml_ul_typeDB
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CheckoutPhaseOneInstance(xhtml_ul_typeDB *Xhtml_ul_typeDB) (Error error) {

	xhtml_ul_type, ok := backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr[xhtml_ul_typeDB.ID]
	if !ok {
		xhtml_ul_type = new(models.Xhtml_ul_type)

		backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr[xhtml_ul_typeDB.ID] = xhtml_ul_type
		backRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID[xhtml_ul_type] = xhtml_ul_typeDB.ID

		// append model store with the new element
		xhtml_ul_type.Name = xhtml_ul_typeDB.Name_Data.String
		xhtml_ul_type.Stage(backRepoXhtml_ul_type.GetStage())
	}
	xhtml_ul_typeDB.CopyBasicFieldsToXhtml_ul_type(xhtml_ul_type)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	xhtml_ul_type.Stage(backRepoXhtml_ul_type.GetStage())

	// preserve pointer to xhtml_ul_typeDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB)[xhtml_ul_typeDB hold variable pointers
	xhtml_ul_typeDB_Data := *xhtml_ul_typeDB
	preservedPtrToXhtml_ul_type := &xhtml_ul_typeDB_Data
	backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB[xhtml_ul_typeDB.ID] = preservedPtrToXhtml_ul_type

	return
}

// BackRepoXhtml_ul_type.CheckoutPhaseTwo Checkouts all staged instances of Xhtml_ul_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, xhtml_ul_typeDB := range backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB {
		backRepoXhtml_ul_type.CheckoutPhaseTwoInstance(backRepo, xhtml_ul_typeDB)
	}
	return
}

// BackRepoXhtml_ul_type.CheckoutPhaseTwoInstance Checkouts staged instances of Xhtml_ul_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, xhtml_ul_typeDB *Xhtml_ul_typeDB) (Error error) {

	xhtml_ul_type := backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr[xhtml_ul_typeDB.ID]

	xhtml_ul_typeDB.DecodePointers(backRepo, xhtml_ul_type)

	return
}

func (xhtml_ul_typeDB *Xhtml_ul_typeDB) DecodePointers(backRepo *BackRepoStruct, xhtml_ul_type *models.Xhtml_ul_type) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitXhtml_ul_type allows commit of a single xhtml_ul_type (if already staged)
func (backRepo *BackRepoStruct) CommitXhtml_ul_type(xhtml_ul_type *models.Xhtml_ul_type) {
	backRepo.BackRepoXhtml_ul_type.CommitPhaseOneInstance(xhtml_ul_type)
	if id, ok := backRepo.BackRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID[xhtml_ul_type]; ok {
		backRepo.BackRepoXhtml_ul_type.CommitPhaseTwoInstance(backRepo, id, xhtml_ul_type)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitXhtml_ul_type allows checkout of a single xhtml_ul_type (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutXhtml_ul_type(xhtml_ul_type *models.Xhtml_ul_type) {
	// check if the xhtml_ul_type is staged
	if _, ok := backRepo.BackRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID[xhtml_ul_type]; ok {

		if id, ok := backRepo.BackRepoXhtml_ul_type.Map_Xhtml_ul_typePtr_Xhtml_ul_typeDBID[xhtml_ul_type]; ok {
			var xhtml_ul_typeDB Xhtml_ul_typeDB
			xhtml_ul_typeDB.ID = id

			if _, err := backRepo.BackRepoXhtml_ul_type.db.First(&xhtml_ul_typeDB, id); err != nil {
				log.Fatalln("CheckoutXhtml_ul_type : Problem with getting object with id:", id)
			}
			backRepo.BackRepoXhtml_ul_type.CheckoutPhaseOneInstance(&xhtml_ul_typeDB)
			backRepo.BackRepoXhtml_ul_type.CheckoutPhaseTwoInstance(backRepo, &xhtml_ul_typeDB)
		}
	}
}

// CopyBasicFieldsFromXhtml_ul_type
func (xhtml_ul_typeDB *Xhtml_ul_typeDB) CopyBasicFieldsFromXhtml_ul_type(xhtml_ul_type *models.Xhtml_ul_type) {
	// insertion point for fields commit

	xhtml_ul_typeDB.Name_Data.String = xhtml_ul_type.Name
	xhtml_ul_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_ul_type_WOP
func (xhtml_ul_typeDB *Xhtml_ul_typeDB) CopyBasicFieldsFromXhtml_ul_type_WOP(xhtml_ul_type *models.Xhtml_ul_type_WOP) {
	// insertion point for fields commit

	xhtml_ul_typeDB.Name_Data.String = xhtml_ul_type.Name
	xhtml_ul_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_ul_typeWOP
func (xhtml_ul_typeDB *Xhtml_ul_typeDB) CopyBasicFieldsFromXhtml_ul_typeWOP(xhtml_ul_type *Xhtml_ul_typeWOP) {
	// insertion point for fields commit

	xhtml_ul_typeDB.Name_Data.String = xhtml_ul_type.Name
	xhtml_ul_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsToXhtml_ul_type
func (xhtml_ul_typeDB *Xhtml_ul_typeDB) CopyBasicFieldsToXhtml_ul_type(xhtml_ul_type *models.Xhtml_ul_type) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_ul_type.Name = xhtml_ul_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_ul_type_WOP
func (xhtml_ul_typeDB *Xhtml_ul_typeDB) CopyBasicFieldsToXhtml_ul_type_WOP(xhtml_ul_type *models.Xhtml_ul_type_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_ul_type.Name = xhtml_ul_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_ul_typeWOP
func (xhtml_ul_typeDB *Xhtml_ul_typeDB) CopyBasicFieldsToXhtml_ul_typeWOP(xhtml_ul_type *Xhtml_ul_typeWOP) {
	xhtml_ul_type.ID = int(xhtml_ul_typeDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_ul_type.Name = xhtml_ul_typeDB.Name_Data.String
}

// Backup generates a json file from a slice of all Xhtml_ul_typeDB instances in the backrepo
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "Xhtml_ul_typeDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_ul_typeDB, 0)
	for _, xhtml_ul_typeDB := range backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB {
		forBackup = append(forBackup, xhtml_ul_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json Xhtml_ul_type ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json Xhtml_ul_type file", err.Error())
	}
}

// Backup generates a json file from a slice of all Xhtml_ul_typeDB instances in the backrepo
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_ul_typeDB, 0)
	for _, xhtml_ul_typeDB := range backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB {
		forBackup = append(forBackup, xhtml_ul_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Xhtml_ul_type")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Xhtml_ul_type_Fields, -1)
	for _, xhtml_ul_typeDB := range forBackup {

		var xhtml_ul_typeWOP Xhtml_ul_typeWOP
		xhtml_ul_typeDB.CopyBasicFieldsToXhtml_ul_typeWOP(&xhtml_ul_typeWOP)

		row := sh.AddRow()
		row.WriteStruct(&xhtml_ul_typeWOP, -1)
	}
}

// RestoreXL from the "Xhtml_ul_type" sheet all Xhtml_ul_typeDB instances
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoXhtml_ul_typeid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Xhtml_ul_type"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoXhtml_ul_type.rowVisitorXhtml_ul_type)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) rowVisitorXhtml_ul_type(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var xhtml_ul_typeWOP Xhtml_ul_typeWOP
		row.ReadStruct(&xhtml_ul_typeWOP)

		// add the unmarshalled struct to the stage
		xhtml_ul_typeDB := new(Xhtml_ul_typeDB)
		xhtml_ul_typeDB.CopyBasicFieldsFromXhtml_ul_typeWOP(&xhtml_ul_typeWOP)

		xhtml_ul_typeDB_ID_atBackupTime := xhtml_ul_typeDB.ID
		xhtml_ul_typeDB.ID = 0
		_, err := backRepoXhtml_ul_type.db.Create(xhtml_ul_typeDB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB[xhtml_ul_typeDB.ID] = xhtml_ul_typeDB
		BackRepoXhtml_ul_typeid_atBckpTime_newID[xhtml_ul_typeDB_ID_atBackupTime] = xhtml_ul_typeDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "Xhtml_ul_typeDB.json" in dirPath that stores an array
// of Xhtml_ul_typeDB and stores it in the database
// the map BackRepoXhtml_ul_typeid_atBckpTime_newID is updated accordingly
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoXhtml_ul_typeid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "Xhtml_ul_typeDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json Xhtml_ul_type file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*Xhtml_ul_typeDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB
	for _, xhtml_ul_typeDB := range forRestore {

		xhtml_ul_typeDB_ID_atBackupTime := xhtml_ul_typeDB.ID
		xhtml_ul_typeDB.ID = 0
		_, err := backRepoXhtml_ul_type.db.Create(xhtml_ul_typeDB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB[xhtml_ul_typeDB.ID] = xhtml_ul_typeDB
		BackRepoXhtml_ul_typeid_atBckpTime_newID[xhtml_ul_typeDB_ID_atBackupTime] = xhtml_ul_typeDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json Xhtml_ul_type file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Xhtml_ul_type>id_atBckpTime_newID
// to compute new index
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) RestorePhaseTwo() {

	for _, xhtml_ul_typeDB := range backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB {

		// next line of code is to avert unused variable compilation error
		_ = xhtml_ul_typeDB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		db, _ := backRepoXhtml_ul_type.db.Model(xhtml_ul_typeDB)
		_, err := db.Updates(*xhtml_ul_typeDB)
		if err != nil {
			log.Fatal(err)
		}
	}

}

// BackRepoXhtml_ul_type.ResetReversePointers commits all staged instances of Xhtml_ul_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_ul_type := range backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typePtr {
		backRepoXhtml_ul_type.ResetReversePointersInstance(backRepo, idx, xhtml_ul_type)
	}

	return
}

func (backRepoXhtml_ul_type *BackRepoXhtml_ul_typeStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, xhtml_ul_type *models.Xhtml_ul_type) (Error error) {

	// fetch matching xhtml_ul_typeDB
	if xhtml_ul_typeDB, ok := backRepoXhtml_ul_type.Map_Xhtml_ul_typeDBID_Xhtml_ul_typeDB[idx]; ok {
		_ = xhtml_ul_typeDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoXhtml_ul_typeid_atBckpTime_newID map[uint]uint
