// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongreqif/go/db"
	"github.com/fullstack-lang/gongreqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Xhtml_tbody_type_sql sql.NullBool
var dummy_Xhtml_tbody_type_time time.Duration
var dummy_Xhtml_tbody_type_sort sort.Float64Slice

// Xhtml_tbody_typeAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model xhtml_tbody_typeAPI
type Xhtml_tbody_typeAPI struct {
	gorm.Model

	models.Xhtml_tbody_type_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	Xhtml_tbody_typePointersEncoding Xhtml_tbody_typePointersEncoding
}

// Xhtml_tbody_typePointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type Xhtml_tbody_typePointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// Xhtml_tbody_typeDB describes a xhtml_tbody_type in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model xhtml_tbody_typeDB
type Xhtml_tbody_typeDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field xhtml_tbody_typeDB.Name
	Name_Data sql.NullString

	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	Xhtml_tbody_typePointersEncoding
}

// Xhtml_tbody_typeDBs arrays xhtml_tbody_typeDBs
// swagger:response xhtml_tbody_typeDBsResponse
type Xhtml_tbody_typeDBs []Xhtml_tbody_typeDB

// Xhtml_tbody_typeDBResponse provides response
// swagger:response xhtml_tbody_typeDBResponse
type Xhtml_tbody_typeDBResponse struct {
	Xhtml_tbody_typeDB
}

// Xhtml_tbody_typeWOP is a Xhtml_tbody_type without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type Xhtml_tbody_typeWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`
	// insertion for WOP pointer fields
}

var Xhtml_tbody_type_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
}

type BackRepoXhtml_tbody_typeStruct struct {
	// stores Xhtml_tbody_typeDB according to their gorm ID
	Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB map[uint]*Xhtml_tbody_typeDB

	// stores Xhtml_tbody_typeDB ID according to Xhtml_tbody_type address
	Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID map[*models.Xhtml_tbody_type]uint

	// stores Xhtml_tbody_type according to their gorm ID
	Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr map[uint]*models.Xhtml_tbody_type

	db db.DBInterface

	stage *models.Stage
}

func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) GetStage() (stage *models.Stage) {
	stage = backRepoXhtml_tbody_type.stage
	return
}

func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) GetDB() db.DBInterface {
	return backRepoXhtml_tbody_type.db
}

// GetXhtml_tbody_typeDBFromXhtml_tbody_typePtr is a handy function to access the back repo instance from the stage instance
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) GetXhtml_tbody_typeDBFromXhtml_tbody_typePtr(xhtml_tbody_type *models.Xhtml_tbody_type) (xhtml_tbody_typeDB *Xhtml_tbody_typeDB) {
	id := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID[xhtml_tbody_type]
	xhtml_tbody_typeDB = backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB[id]
	return
}

// BackRepoXhtml_tbody_type.CommitPhaseOne commits all staged instances of Xhtml_tbody_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CommitPhaseOne(stage *models.Stage) (Error error) {

	var xhtml_tbody_types []*models.Xhtml_tbody_type
	for xhtml_tbody_type := range stage.Xhtml_tbody_types {
		xhtml_tbody_types = append(xhtml_tbody_types, xhtml_tbody_type)
	}

	// Sort by the order stored in Map_Staged_Order.
	sort.Slice(xhtml_tbody_types, func(i, j int) bool {
		return stage.Xhtml_tbody_typeMap_Staged_Order[xhtml_tbody_types[i]] < stage.Xhtml_tbody_typeMap_Staged_Order[xhtml_tbody_types[j]]
	})

	for _, xhtml_tbody_type := range xhtml_tbody_types {
		backRepoXhtml_tbody_type.CommitPhaseOneInstance(xhtml_tbody_type)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, xhtml_tbody_type := range backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr {
		if _, ok := stage.Xhtml_tbody_types[xhtml_tbody_type]; !ok {
			backRepoXhtml_tbody_type.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoXhtml_tbody_type.CommitDeleteInstance commits deletion of Xhtml_tbody_type to the BackRepo
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CommitDeleteInstance(id uint) (Error error) {

	xhtml_tbody_type := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr[id]

	// xhtml_tbody_type is not staged anymore, remove xhtml_tbody_typeDB
	xhtml_tbody_typeDB := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB[id]
	db, _ := backRepoXhtml_tbody_type.db.Unscoped()
	_, err := db.Delete(xhtml_tbody_typeDB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	delete(backRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID, xhtml_tbody_type)
	delete(backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr, id)
	delete(backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB, id)

	return
}

// BackRepoXhtml_tbody_type.CommitPhaseOneInstance commits xhtml_tbody_type staged instances of Xhtml_tbody_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CommitPhaseOneInstance(xhtml_tbody_type *models.Xhtml_tbody_type) (Error error) {

	// check if the xhtml_tbody_type is not commited yet
	if _, ok := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID[xhtml_tbody_type]; ok {
		return
	}

	// initiate xhtml_tbody_type
	var xhtml_tbody_typeDB Xhtml_tbody_typeDB
	xhtml_tbody_typeDB.CopyBasicFieldsFromXhtml_tbody_type(xhtml_tbody_type)

	_, err := backRepoXhtml_tbody_type.db.Create(&xhtml_tbody_typeDB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	backRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID[xhtml_tbody_type] = xhtml_tbody_typeDB.ID
	backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr[xhtml_tbody_typeDB.ID] = xhtml_tbody_type
	backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB[xhtml_tbody_typeDB.ID] = &xhtml_tbody_typeDB

	return
}

// BackRepoXhtml_tbody_type.CommitPhaseTwo commits all staged instances of Xhtml_tbody_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_tbody_type := range backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr {
		backRepoXhtml_tbody_type.CommitPhaseTwoInstance(backRepo, idx, xhtml_tbody_type)
	}

	return
}

// BackRepoXhtml_tbody_type.CommitPhaseTwoInstance commits {{structname }} of models.Xhtml_tbody_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, xhtml_tbody_type *models.Xhtml_tbody_type) (Error error) {

	// fetch matching xhtml_tbody_typeDB
	if xhtml_tbody_typeDB, ok := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB[idx]; ok {

		xhtml_tbody_typeDB.CopyBasicFieldsFromXhtml_tbody_type(xhtml_tbody_type)

		// insertion point for translating pointers encodings into actual pointers
		_, err := backRepoXhtml_tbody_type.db.Save(xhtml_tbody_typeDB)
		if err != nil {
			log.Fatal(err)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown Xhtml_tbody_type intance %s", xhtml_tbody_type.Name))
		return err
	}

	return
}

// BackRepoXhtml_tbody_type.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CheckoutPhaseOne() (Error error) {

	xhtml_tbody_typeDBArray := make([]Xhtml_tbody_typeDB, 0)
	_, err := backRepoXhtml_tbody_type.db.Find(&xhtml_tbody_typeDBArray)
	if err != nil {
		return err
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	xhtml_tbody_typeInstancesToBeRemovedFromTheStage := make(map[*models.Xhtml_tbody_type]any)
	for key, value := range backRepoXhtml_tbody_type.stage.Xhtml_tbody_types {
		xhtml_tbody_typeInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, xhtml_tbody_typeDB := range xhtml_tbody_typeDBArray {
		backRepoXhtml_tbody_type.CheckoutPhaseOneInstance(&xhtml_tbody_typeDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		xhtml_tbody_type, ok := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr[xhtml_tbody_typeDB.ID]
		if ok {
			delete(xhtml_tbody_typeInstancesToBeRemovedFromTheStage, xhtml_tbody_type)
		}
	}

	// remove from stage and back repo's 3 maps all xhtml_tbody_types that are not in the checkout
	for xhtml_tbody_type := range xhtml_tbody_typeInstancesToBeRemovedFromTheStage {
		xhtml_tbody_type.Unstage(backRepoXhtml_tbody_type.GetStage())

		// remove instance from the back repo 3 maps
		xhtml_tbody_typeID := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID[xhtml_tbody_type]
		delete(backRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID, xhtml_tbody_type)
		delete(backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB, xhtml_tbody_typeID)
		delete(backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr, xhtml_tbody_typeID)
	}

	return
}

// CheckoutPhaseOneInstance takes a xhtml_tbody_typeDB that has been found in the DB, updates the backRepo and stages the
// models version of the xhtml_tbody_typeDB
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CheckoutPhaseOneInstance(xhtml_tbody_typeDB *Xhtml_tbody_typeDB) (Error error) {

	xhtml_tbody_type, ok := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr[xhtml_tbody_typeDB.ID]
	if !ok {
		xhtml_tbody_type = new(models.Xhtml_tbody_type)

		backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr[xhtml_tbody_typeDB.ID] = xhtml_tbody_type
		backRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID[xhtml_tbody_type] = xhtml_tbody_typeDB.ID

		// append model store with the new element
		xhtml_tbody_type.Name = xhtml_tbody_typeDB.Name_Data.String
		xhtml_tbody_type.Stage(backRepoXhtml_tbody_type.GetStage())
	}
	xhtml_tbody_typeDB.CopyBasicFieldsToXhtml_tbody_type(xhtml_tbody_type)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	xhtml_tbody_type.Stage(backRepoXhtml_tbody_type.GetStage())

	// preserve pointer to xhtml_tbody_typeDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB)[xhtml_tbody_typeDB hold variable pointers
	xhtml_tbody_typeDB_Data := *xhtml_tbody_typeDB
	preservedPtrToXhtml_tbody_type := &xhtml_tbody_typeDB_Data
	backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB[xhtml_tbody_typeDB.ID] = preservedPtrToXhtml_tbody_type

	return
}

// BackRepoXhtml_tbody_type.CheckoutPhaseTwo Checkouts all staged instances of Xhtml_tbody_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, xhtml_tbody_typeDB := range backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB {
		backRepoXhtml_tbody_type.CheckoutPhaseTwoInstance(backRepo, xhtml_tbody_typeDB)
	}
	return
}

// BackRepoXhtml_tbody_type.CheckoutPhaseTwoInstance Checkouts staged instances of Xhtml_tbody_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, xhtml_tbody_typeDB *Xhtml_tbody_typeDB) (Error error) {

	xhtml_tbody_type := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr[xhtml_tbody_typeDB.ID]

	xhtml_tbody_typeDB.DecodePointers(backRepo, xhtml_tbody_type)

	return
}

func (xhtml_tbody_typeDB *Xhtml_tbody_typeDB) DecodePointers(backRepo *BackRepoStruct, xhtml_tbody_type *models.Xhtml_tbody_type) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitXhtml_tbody_type allows commit of a single xhtml_tbody_type (if already staged)
func (backRepo *BackRepoStruct) CommitXhtml_tbody_type(xhtml_tbody_type *models.Xhtml_tbody_type) {
	backRepo.BackRepoXhtml_tbody_type.CommitPhaseOneInstance(xhtml_tbody_type)
	if id, ok := backRepo.BackRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID[xhtml_tbody_type]; ok {
		backRepo.BackRepoXhtml_tbody_type.CommitPhaseTwoInstance(backRepo, id, xhtml_tbody_type)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitXhtml_tbody_type allows checkout of a single xhtml_tbody_type (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutXhtml_tbody_type(xhtml_tbody_type *models.Xhtml_tbody_type) {
	// check if the xhtml_tbody_type is staged
	if _, ok := backRepo.BackRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID[xhtml_tbody_type]; ok {

		if id, ok := backRepo.BackRepoXhtml_tbody_type.Map_Xhtml_tbody_typePtr_Xhtml_tbody_typeDBID[xhtml_tbody_type]; ok {
			var xhtml_tbody_typeDB Xhtml_tbody_typeDB
			xhtml_tbody_typeDB.ID = id

			if _, err := backRepo.BackRepoXhtml_tbody_type.db.First(&xhtml_tbody_typeDB, id); err != nil {
				log.Fatalln("CheckoutXhtml_tbody_type : Problem with getting object with id:", id)
			}
			backRepo.BackRepoXhtml_tbody_type.CheckoutPhaseOneInstance(&xhtml_tbody_typeDB)
			backRepo.BackRepoXhtml_tbody_type.CheckoutPhaseTwoInstance(backRepo, &xhtml_tbody_typeDB)
		}
	}
}

// CopyBasicFieldsFromXhtml_tbody_type
func (xhtml_tbody_typeDB *Xhtml_tbody_typeDB) CopyBasicFieldsFromXhtml_tbody_type(xhtml_tbody_type *models.Xhtml_tbody_type) {
	// insertion point for fields commit

	xhtml_tbody_typeDB.Name_Data.String = xhtml_tbody_type.Name
	xhtml_tbody_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_tbody_type_WOP
func (xhtml_tbody_typeDB *Xhtml_tbody_typeDB) CopyBasicFieldsFromXhtml_tbody_type_WOP(xhtml_tbody_type *models.Xhtml_tbody_type_WOP) {
	// insertion point for fields commit

	xhtml_tbody_typeDB.Name_Data.String = xhtml_tbody_type.Name
	xhtml_tbody_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_tbody_typeWOP
func (xhtml_tbody_typeDB *Xhtml_tbody_typeDB) CopyBasicFieldsFromXhtml_tbody_typeWOP(xhtml_tbody_type *Xhtml_tbody_typeWOP) {
	// insertion point for fields commit

	xhtml_tbody_typeDB.Name_Data.String = xhtml_tbody_type.Name
	xhtml_tbody_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsToXhtml_tbody_type
func (xhtml_tbody_typeDB *Xhtml_tbody_typeDB) CopyBasicFieldsToXhtml_tbody_type(xhtml_tbody_type *models.Xhtml_tbody_type) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_tbody_type.Name = xhtml_tbody_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_tbody_type_WOP
func (xhtml_tbody_typeDB *Xhtml_tbody_typeDB) CopyBasicFieldsToXhtml_tbody_type_WOP(xhtml_tbody_type *models.Xhtml_tbody_type_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_tbody_type.Name = xhtml_tbody_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_tbody_typeWOP
func (xhtml_tbody_typeDB *Xhtml_tbody_typeDB) CopyBasicFieldsToXhtml_tbody_typeWOP(xhtml_tbody_type *Xhtml_tbody_typeWOP) {
	xhtml_tbody_type.ID = int(xhtml_tbody_typeDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_tbody_type.Name = xhtml_tbody_typeDB.Name_Data.String
}

// Backup generates a json file from a slice of all Xhtml_tbody_typeDB instances in the backrepo
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "Xhtml_tbody_typeDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_tbody_typeDB, 0)
	for _, xhtml_tbody_typeDB := range backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB {
		forBackup = append(forBackup, xhtml_tbody_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json Xhtml_tbody_type ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json Xhtml_tbody_type file", err.Error())
	}
}

// Backup generates a json file from a slice of all Xhtml_tbody_typeDB instances in the backrepo
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_tbody_typeDB, 0)
	for _, xhtml_tbody_typeDB := range backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB {
		forBackup = append(forBackup, xhtml_tbody_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Xhtml_tbody_type")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Xhtml_tbody_type_Fields, -1)
	for _, xhtml_tbody_typeDB := range forBackup {

		var xhtml_tbody_typeWOP Xhtml_tbody_typeWOP
		xhtml_tbody_typeDB.CopyBasicFieldsToXhtml_tbody_typeWOP(&xhtml_tbody_typeWOP)

		row := sh.AddRow()
		row.WriteStruct(&xhtml_tbody_typeWOP, -1)
	}
}

// RestoreXL from the "Xhtml_tbody_type" sheet all Xhtml_tbody_typeDB instances
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoXhtml_tbody_typeid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Xhtml_tbody_type"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoXhtml_tbody_type.rowVisitorXhtml_tbody_type)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) rowVisitorXhtml_tbody_type(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var xhtml_tbody_typeWOP Xhtml_tbody_typeWOP
		row.ReadStruct(&xhtml_tbody_typeWOP)

		// add the unmarshalled struct to the stage
		xhtml_tbody_typeDB := new(Xhtml_tbody_typeDB)
		xhtml_tbody_typeDB.CopyBasicFieldsFromXhtml_tbody_typeWOP(&xhtml_tbody_typeWOP)

		xhtml_tbody_typeDB_ID_atBackupTime := xhtml_tbody_typeDB.ID
		xhtml_tbody_typeDB.ID = 0
		_, err := backRepoXhtml_tbody_type.db.Create(xhtml_tbody_typeDB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB[xhtml_tbody_typeDB.ID] = xhtml_tbody_typeDB
		BackRepoXhtml_tbody_typeid_atBckpTime_newID[xhtml_tbody_typeDB_ID_atBackupTime] = xhtml_tbody_typeDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "Xhtml_tbody_typeDB.json" in dirPath that stores an array
// of Xhtml_tbody_typeDB and stores it in the database
// the map BackRepoXhtml_tbody_typeid_atBckpTime_newID is updated accordingly
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoXhtml_tbody_typeid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "Xhtml_tbody_typeDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json Xhtml_tbody_type file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*Xhtml_tbody_typeDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB
	for _, xhtml_tbody_typeDB := range forRestore {

		xhtml_tbody_typeDB_ID_atBackupTime := xhtml_tbody_typeDB.ID
		xhtml_tbody_typeDB.ID = 0
		_, err := backRepoXhtml_tbody_type.db.Create(xhtml_tbody_typeDB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB[xhtml_tbody_typeDB.ID] = xhtml_tbody_typeDB
		BackRepoXhtml_tbody_typeid_atBckpTime_newID[xhtml_tbody_typeDB_ID_atBackupTime] = xhtml_tbody_typeDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json Xhtml_tbody_type file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Xhtml_tbody_type>id_atBckpTime_newID
// to compute new index
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) RestorePhaseTwo() {

	for _, xhtml_tbody_typeDB := range backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB {

		// next line of code is to avert unused variable compilation error
		_ = xhtml_tbody_typeDB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		db, _ := backRepoXhtml_tbody_type.db.Model(xhtml_tbody_typeDB)
		_, err := db.Updates(*xhtml_tbody_typeDB)
		if err != nil {
			log.Fatal(err)
		}
	}

}

// BackRepoXhtml_tbody_type.ResetReversePointers commits all staged instances of Xhtml_tbody_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_tbody_type := range backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typePtr {
		backRepoXhtml_tbody_type.ResetReversePointersInstance(backRepo, idx, xhtml_tbody_type)
	}

	return
}

func (backRepoXhtml_tbody_type *BackRepoXhtml_tbody_typeStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, xhtml_tbody_type *models.Xhtml_tbody_type) (Error error) {

	// fetch matching xhtml_tbody_typeDB
	if xhtml_tbody_typeDB, ok := backRepoXhtml_tbody_type.Map_Xhtml_tbody_typeDBID_Xhtml_tbody_typeDB[idx]; ok {
		_ = xhtml_tbody_typeDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoXhtml_tbody_typeid_atBckpTime_newID map[uint]uint
