// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongreqif/go/db"
	"github.com/fullstack-lang/gongreqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Xhtml_em_type_sql sql.NullBool
var dummy_Xhtml_em_type_time time.Duration
var dummy_Xhtml_em_type_sort sort.Float64Slice

// Xhtml_em_typeAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model xhtml_em_typeAPI
type Xhtml_em_typeAPI struct {
	gorm.Model

	models.Xhtml_em_type_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	Xhtml_em_typePointersEncoding Xhtml_em_typePointersEncoding
}

// Xhtml_em_typePointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type Xhtml_em_typePointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// Xhtml_em_typeDB describes a xhtml_em_type in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model xhtml_em_typeDB
type Xhtml_em_typeDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field xhtml_em_typeDB.Name
	Name_Data sql.NullString

	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	Xhtml_em_typePointersEncoding
}

// Xhtml_em_typeDBs arrays xhtml_em_typeDBs
// swagger:response xhtml_em_typeDBsResponse
type Xhtml_em_typeDBs []Xhtml_em_typeDB

// Xhtml_em_typeDBResponse provides response
// swagger:response xhtml_em_typeDBResponse
type Xhtml_em_typeDBResponse struct {
	Xhtml_em_typeDB
}

// Xhtml_em_typeWOP is a Xhtml_em_type without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type Xhtml_em_typeWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`
	// insertion for WOP pointer fields
}

var Xhtml_em_type_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
}

type BackRepoXhtml_em_typeStruct struct {
	// stores Xhtml_em_typeDB according to their gorm ID
	Map_Xhtml_em_typeDBID_Xhtml_em_typeDB map[uint]*Xhtml_em_typeDB

	// stores Xhtml_em_typeDB ID according to Xhtml_em_type address
	Map_Xhtml_em_typePtr_Xhtml_em_typeDBID map[*models.Xhtml_em_type]uint

	// stores Xhtml_em_type according to their gorm ID
	Map_Xhtml_em_typeDBID_Xhtml_em_typePtr map[uint]*models.Xhtml_em_type

	db db.DBInterface

	stage *models.Stage
}

func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) GetStage() (stage *models.Stage) {
	stage = backRepoXhtml_em_type.stage
	return
}

func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) GetDB() db.DBInterface {
	return backRepoXhtml_em_type.db
}

// GetXhtml_em_typeDBFromXhtml_em_typePtr is a handy function to access the back repo instance from the stage instance
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) GetXhtml_em_typeDBFromXhtml_em_typePtr(xhtml_em_type *models.Xhtml_em_type) (xhtml_em_typeDB *Xhtml_em_typeDB) {
	id := backRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID[xhtml_em_type]
	xhtml_em_typeDB = backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB[id]
	return
}

// BackRepoXhtml_em_type.CommitPhaseOne commits all staged instances of Xhtml_em_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CommitPhaseOne(stage *models.Stage) (Error error) {

	var xhtml_em_types []*models.Xhtml_em_type
	for xhtml_em_type := range stage.Xhtml_em_types {
		xhtml_em_types = append(xhtml_em_types, xhtml_em_type)
	}

	// Sort by the order stored in Map_Staged_Order.
	sort.Slice(xhtml_em_types, func(i, j int) bool {
		return stage.Xhtml_em_typeMap_Staged_Order[xhtml_em_types[i]] < stage.Xhtml_em_typeMap_Staged_Order[xhtml_em_types[j]]
	})

	for _, xhtml_em_type := range xhtml_em_types {
		backRepoXhtml_em_type.CommitPhaseOneInstance(xhtml_em_type)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, xhtml_em_type := range backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr {
		if _, ok := stage.Xhtml_em_types[xhtml_em_type]; !ok {
			backRepoXhtml_em_type.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoXhtml_em_type.CommitDeleteInstance commits deletion of Xhtml_em_type to the BackRepo
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CommitDeleteInstance(id uint) (Error error) {

	xhtml_em_type := backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr[id]

	// xhtml_em_type is not staged anymore, remove xhtml_em_typeDB
	xhtml_em_typeDB := backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB[id]
	db, _ := backRepoXhtml_em_type.db.Unscoped()
	_, err := db.Delete(xhtml_em_typeDB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	delete(backRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID, xhtml_em_type)
	delete(backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr, id)
	delete(backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB, id)

	return
}

// BackRepoXhtml_em_type.CommitPhaseOneInstance commits xhtml_em_type staged instances of Xhtml_em_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CommitPhaseOneInstance(xhtml_em_type *models.Xhtml_em_type) (Error error) {

	// check if the xhtml_em_type is not commited yet
	if _, ok := backRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID[xhtml_em_type]; ok {
		return
	}

	// initiate xhtml_em_type
	var xhtml_em_typeDB Xhtml_em_typeDB
	xhtml_em_typeDB.CopyBasicFieldsFromXhtml_em_type(xhtml_em_type)

	_, err := backRepoXhtml_em_type.db.Create(&xhtml_em_typeDB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	backRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID[xhtml_em_type] = xhtml_em_typeDB.ID
	backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr[xhtml_em_typeDB.ID] = xhtml_em_type
	backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB[xhtml_em_typeDB.ID] = &xhtml_em_typeDB

	return
}

// BackRepoXhtml_em_type.CommitPhaseTwo commits all staged instances of Xhtml_em_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_em_type := range backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr {
		backRepoXhtml_em_type.CommitPhaseTwoInstance(backRepo, idx, xhtml_em_type)
	}

	return
}

// BackRepoXhtml_em_type.CommitPhaseTwoInstance commits {{structname }} of models.Xhtml_em_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, xhtml_em_type *models.Xhtml_em_type) (Error error) {

	// fetch matching xhtml_em_typeDB
	if xhtml_em_typeDB, ok := backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB[idx]; ok {

		xhtml_em_typeDB.CopyBasicFieldsFromXhtml_em_type(xhtml_em_type)

		// insertion point for translating pointers encodings into actual pointers
		_, err := backRepoXhtml_em_type.db.Save(xhtml_em_typeDB)
		if err != nil {
			log.Fatal(err)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown Xhtml_em_type intance %s", xhtml_em_type.Name))
		return err
	}

	return
}

// BackRepoXhtml_em_type.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CheckoutPhaseOne() (Error error) {

	xhtml_em_typeDBArray := make([]Xhtml_em_typeDB, 0)
	_, err := backRepoXhtml_em_type.db.Find(&xhtml_em_typeDBArray)
	if err != nil {
		return err
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	xhtml_em_typeInstancesToBeRemovedFromTheStage := make(map[*models.Xhtml_em_type]any)
	for key, value := range backRepoXhtml_em_type.stage.Xhtml_em_types {
		xhtml_em_typeInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, xhtml_em_typeDB := range xhtml_em_typeDBArray {
		backRepoXhtml_em_type.CheckoutPhaseOneInstance(&xhtml_em_typeDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		xhtml_em_type, ok := backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr[xhtml_em_typeDB.ID]
		if ok {
			delete(xhtml_em_typeInstancesToBeRemovedFromTheStage, xhtml_em_type)
		}
	}

	// remove from stage and back repo's 3 maps all xhtml_em_types that are not in the checkout
	for xhtml_em_type := range xhtml_em_typeInstancesToBeRemovedFromTheStage {
		xhtml_em_type.Unstage(backRepoXhtml_em_type.GetStage())

		// remove instance from the back repo 3 maps
		xhtml_em_typeID := backRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID[xhtml_em_type]
		delete(backRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID, xhtml_em_type)
		delete(backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB, xhtml_em_typeID)
		delete(backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr, xhtml_em_typeID)
	}

	return
}

// CheckoutPhaseOneInstance takes a xhtml_em_typeDB that has been found in the DB, updates the backRepo and stages the
// models version of the xhtml_em_typeDB
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CheckoutPhaseOneInstance(xhtml_em_typeDB *Xhtml_em_typeDB) (Error error) {

	xhtml_em_type, ok := backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr[xhtml_em_typeDB.ID]
	if !ok {
		xhtml_em_type = new(models.Xhtml_em_type)

		backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr[xhtml_em_typeDB.ID] = xhtml_em_type
		backRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID[xhtml_em_type] = xhtml_em_typeDB.ID

		// append model store with the new element
		xhtml_em_type.Name = xhtml_em_typeDB.Name_Data.String
		xhtml_em_type.Stage(backRepoXhtml_em_type.GetStage())
	}
	xhtml_em_typeDB.CopyBasicFieldsToXhtml_em_type(xhtml_em_type)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	xhtml_em_type.Stage(backRepoXhtml_em_type.GetStage())

	// preserve pointer to xhtml_em_typeDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_Xhtml_em_typeDBID_Xhtml_em_typeDB)[xhtml_em_typeDB hold variable pointers
	xhtml_em_typeDB_Data := *xhtml_em_typeDB
	preservedPtrToXhtml_em_type := &xhtml_em_typeDB_Data
	backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB[xhtml_em_typeDB.ID] = preservedPtrToXhtml_em_type

	return
}

// BackRepoXhtml_em_type.CheckoutPhaseTwo Checkouts all staged instances of Xhtml_em_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, xhtml_em_typeDB := range backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB {
		backRepoXhtml_em_type.CheckoutPhaseTwoInstance(backRepo, xhtml_em_typeDB)
	}
	return
}

// BackRepoXhtml_em_type.CheckoutPhaseTwoInstance Checkouts staged instances of Xhtml_em_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, xhtml_em_typeDB *Xhtml_em_typeDB) (Error error) {

	xhtml_em_type := backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr[xhtml_em_typeDB.ID]

	xhtml_em_typeDB.DecodePointers(backRepo, xhtml_em_type)

	return
}

func (xhtml_em_typeDB *Xhtml_em_typeDB) DecodePointers(backRepo *BackRepoStruct, xhtml_em_type *models.Xhtml_em_type) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitXhtml_em_type allows commit of a single xhtml_em_type (if already staged)
func (backRepo *BackRepoStruct) CommitXhtml_em_type(xhtml_em_type *models.Xhtml_em_type) {
	backRepo.BackRepoXhtml_em_type.CommitPhaseOneInstance(xhtml_em_type)
	if id, ok := backRepo.BackRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID[xhtml_em_type]; ok {
		backRepo.BackRepoXhtml_em_type.CommitPhaseTwoInstance(backRepo, id, xhtml_em_type)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitXhtml_em_type allows checkout of a single xhtml_em_type (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutXhtml_em_type(xhtml_em_type *models.Xhtml_em_type) {
	// check if the xhtml_em_type is staged
	if _, ok := backRepo.BackRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID[xhtml_em_type]; ok {

		if id, ok := backRepo.BackRepoXhtml_em_type.Map_Xhtml_em_typePtr_Xhtml_em_typeDBID[xhtml_em_type]; ok {
			var xhtml_em_typeDB Xhtml_em_typeDB
			xhtml_em_typeDB.ID = id

			if _, err := backRepo.BackRepoXhtml_em_type.db.First(&xhtml_em_typeDB, id); err != nil {
				log.Fatalln("CheckoutXhtml_em_type : Problem with getting object with id:", id)
			}
			backRepo.BackRepoXhtml_em_type.CheckoutPhaseOneInstance(&xhtml_em_typeDB)
			backRepo.BackRepoXhtml_em_type.CheckoutPhaseTwoInstance(backRepo, &xhtml_em_typeDB)
		}
	}
}

// CopyBasicFieldsFromXhtml_em_type
func (xhtml_em_typeDB *Xhtml_em_typeDB) CopyBasicFieldsFromXhtml_em_type(xhtml_em_type *models.Xhtml_em_type) {
	// insertion point for fields commit

	xhtml_em_typeDB.Name_Data.String = xhtml_em_type.Name
	xhtml_em_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_em_type_WOP
func (xhtml_em_typeDB *Xhtml_em_typeDB) CopyBasicFieldsFromXhtml_em_type_WOP(xhtml_em_type *models.Xhtml_em_type_WOP) {
	// insertion point for fields commit

	xhtml_em_typeDB.Name_Data.String = xhtml_em_type.Name
	xhtml_em_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_em_typeWOP
func (xhtml_em_typeDB *Xhtml_em_typeDB) CopyBasicFieldsFromXhtml_em_typeWOP(xhtml_em_type *Xhtml_em_typeWOP) {
	// insertion point for fields commit

	xhtml_em_typeDB.Name_Data.String = xhtml_em_type.Name
	xhtml_em_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsToXhtml_em_type
func (xhtml_em_typeDB *Xhtml_em_typeDB) CopyBasicFieldsToXhtml_em_type(xhtml_em_type *models.Xhtml_em_type) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_em_type.Name = xhtml_em_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_em_type_WOP
func (xhtml_em_typeDB *Xhtml_em_typeDB) CopyBasicFieldsToXhtml_em_type_WOP(xhtml_em_type *models.Xhtml_em_type_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_em_type.Name = xhtml_em_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_em_typeWOP
func (xhtml_em_typeDB *Xhtml_em_typeDB) CopyBasicFieldsToXhtml_em_typeWOP(xhtml_em_type *Xhtml_em_typeWOP) {
	xhtml_em_type.ID = int(xhtml_em_typeDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_em_type.Name = xhtml_em_typeDB.Name_Data.String
}

// Backup generates a json file from a slice of all Xhtml_em_typeDB instances in the backrepo
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "Xhtml_em_typeDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_em_typeDB, 0)
	for _, xhtml_em_typeDB := range backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB {
		forBackup = append(forBackup, xhtml_em_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json Xhtml_em_type ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json Xhtml_em_type file", err.Error())
	}
}

// Backup generates a json file from a slice of all Xhtml_em_typeDB instances in the backrepo
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_em_typeDB, 0)
	for _, xhtml_em_typeDB := range backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB {
		forBackup = append(forBackup, xhtml_em_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Xhtml_em_type")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Xhtml_em_type_Fields, -1)
	for _, xhtml_em_typeDB := range forBackup {

		var xhtml_em_typeWOP Xhtml_em_typeWOP
		xhtml_em_typeDB.CopyBasicFieldsToXhtml_em_typeWOP(&xhtml_em_typeWOP)

		row := sh.AddRow()
		row.WriteStruct(&xhtml_em_typeWOP, -1)
	}
}

// RestoreXL from the "Xhtml_em_type" sheet all Xhtml_em_typeDB instances
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoXhtml_em_typeid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Xhtml_em_type"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoXhtml_em_type.rowVisitorXhtml_em_type)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) rowVisitorXhtml_em_type(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var xhtml_em_typeWOP Xhtml_em_typeWOP
		row.ReadStruct(&xhtml_em_typeWOP)

		// add the unmarshalled struct to the stage
		xhtml_em_typeDB := new(Xhtml_em_typeDB)
		xhtml_em_typeDB.CopyBasicFieldsFromXhtml_em_typeWOP(&xhtml_em_typeWOP)

		xhtml_em_typeDB_ID_atBackupTime := xhtml_em_typeDB.ID
		xhtml_em_typeDB.ID = 0
		_, err := backRepoXhtml_em_type.db.Create(xhtml_em_typeDB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB[xhtml_em_typeDB.ID] = xhtml_em_typeDB
		BackRepoXhtml_em_typeid_atBckpTime_newID[xhtml_em_typeDB_ID_atBackupTime] = xhtml_em_typeDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "Xhtml_em_typeDB.json" in dirPath that stores an array
// of Xhtml_em_typeDB and stores it in the database
// the map BackRepoXhtml_em_typeid_atBckpTime_newID is updated accordingly
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoXhtml_em_typeid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "Xhtml_em_typeDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json Xhtml_em_type file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*Xhtml_em_typeDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_Xhtml_em_typeDBID_Xhtml_em_typeDB
	for _, xhtml_em_typeDB := range forRestore {

		xhtml_em_typeDB_ID_atBackupTime := xhtml_em_typeDB.ID
		xhtml_em_typeDB.ID = 0
		_, err := backRepoXhtml_em_type.db.Create(xhtml_em_typeDB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB[xhtml_em_typeDB.ID] = xhtml_em_typeDB
		BackRepoXhtml_em_typeid_atBckpTime_newID[xhtml_em_typeDB_ID_atBackupTime] = xhtml_em_typeDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json Xhtml_em_type file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Xhtml_em_type>id_atBckpTime_newID
// to compute new index
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) RestorePhaseTwo() {

	for _, xhtml_em_typeDB := range backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB {

		// next line of code is to avert unused variable compilation error
		_ = xhtml_em_typeDB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		db, _ := backRepoXhtml_em_type.db.Model(xhtml_em_typeDB)
		_, err := db.Updates(*xhtml_em_typeDB)
		if err != nil {
			log.Fatal(err)
		}
	}

}

// BackRepoXhtml_em_type.ResetReversePointers commits all staged instances of Xhtml_em_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_em_type := range backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typePtr {
		backRepoXhtml_em_type.ResetReversePointersInstance(backRepo, idx, xhtml_em_type)
	}

	return
}

func (backRepoXhtml_em_type *BackRepoXhtml_em_typeStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, xhtml_em_type *models.Xhtml_em_type) (Error error) {

	// fetch matching xhtml_em_typeDB
	if xhtml_em_typeDB, ok := backRepoXhtml_em_type.Map_Xhtml_em_typeDBID_Xhtml_em_typeDB[idx]; ok {
		_ = xhtml_em_typeDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoXhtml_em_typeid_atBckpTime_newID map[uint]uint
