// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongreqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Xhtml_ol_type_sql sql.NullBool
var dummy_Xhtml_ol_type_time time.Duration
var dummy_Xhtml_ol_type_sort sort.Float64Slice

// Xhtml_ol_typeAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model xhtml_ol_typeAPI
type Xhtml_ol_typeAPI struct {
	gorm.Model

	models.Xhtml_ol_type_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	Xhtml_ol_typePointersEncoding Xhtml_ol_typePointersEncoding
}

// Xhtml_ol_typePointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type Xhtml_ol_typePointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// Xhtml_ol_typeDB describes a xhtml_ol_type in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model xhtml_ol_typeDB
type Xhtml_ol_typeDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field xhtml_ol_typeDB.Name
	Name_Data sql.NullString
	
	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	Xhtml_ol_typePointersEncoding
}

// Xhtml_ol_typeDBs arrays xhtml_ol_typeDBs
// swagger:response xhtml_ol_typeDBsResponse
type Xhtml_ol_typeDBs []Xhtml_ol_typeDB

// Xhtml_ol_typeDBResponse provides response
// swagger:response xhtml_ol_typeDBResponse
type Xhtml_ol_typeDBResponse struct {
	Xhtml_ol_typeDB
}

// Xhtml_ol_typeWOP is a Xhtml_ol_type without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type Xhtml_ol_typeWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`
	// insertion for WOP pointer fields
}

var Xhtml_ol_type_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
}

type BackRepoXhtml_ol_typeStruct struct {
	// stores Xhtml_ol_typeDB according to their gorm ID
	Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB map[uint]*Xhtml_ol_typeDB

	// stores Xhtml_ol_typeDB ID according to Xhtml_ol_type address
	Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID map[*models.Xhtml_ol_type]uint

	// stores Xhtml_ol_type according to their gorm ID
	Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr map[uint]*models.Xhtml_ol_type

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) GetStage() (stage *models.StageStruct) {
	stage = backRepoXhtml_ol_type.stage
	return
}

func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) GetDB() *gorm.DB {
	return backRepoXhtml_ol_type.db
}

// GetXhtml_ol_typeDBFromXhtml_ol_typePtr is a handy function to access the back repo instance from the stage instance
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) GetXhtml_ol_typeDBFromXhtml_ol_typePtr(xhtml_ol_type *models.Xhtml_ol_type) (xhtml_ol_typeDB *Xhtml_ol_typeDB) {
	id := backRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID[xhtml_ol_type]
	xhtml_ol_typeDB = backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB[id]
	return
}

// BackRepoXhtml_ol_type.CommitPhaseOne commits all staged instances of Xhtml_ol_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for xhtml_ol_type := range stage.Xhtml_ol_types {
		backRepoXhtml_ol_type.CommitPhaseOneInstance(xhtml_ol_type)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, xhtml_ol_type := range backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr {
		if _, ok := stage.Xhtml_ol_types[xhtml_ol_type]; !ok {
			backRepoXhtml_ol_type.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoXhtml_ol_type.CommitDeleteInstance commits deletion of Xhtml_ol_type to the BackRepo
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CommitDeleteInstance(id uint) (Error error) {

	xhtml_ol_type := backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr[id]

	// xhtml_ol_type is not staged anymore, remove xhtml_ol_typeDB
	xhtml_ol_typeDB := backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB[id]
	query := backRepoXhtml_ol_type.db.Unscoped().Delete(&xhtml_ol_typeDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	delete(backRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID, xhtml_ol_type)
	delete(backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr, id)
	delete(backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB, id)

	return
}

// BackRepoXhtml_ol_type.CommitPhaseOneInstance commits xhtml_ol_type staged instances of Xhtml_ol_type to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CommitPhaseOneInstance(xhtml_ol_type *models.Xhtml_ol_type) (Error error) {

	// check if the xhtml_ol_type is not commited yet
	if _, ok := backRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID[xhtml_ol_type]; ok {
		return
	}

	// initiate xhtml_ol_type
	var xhtml_ol_typeDB Xhtml_ol_typeDB
	xhtml_ol_typeDB.CopyBasicFieldsFromXhtml_ol_type(xhtml_ol_type)

	query := backRepoXhtml_ol_type.db.Create(&xhtml_ol_typeDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	backRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID[xhtml_ol_type] = xhtml_ol_typeDB.ID
	backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr[xhtml_ol_typeDB.ID] = xhtml_ol_type
	backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB[xhtml_ol_typeDB.ID] = &xhtml_ol_typeDB

	return
}

// BackRepoXhtml_ol_type.CommitPhaseTwo commits all staged instances of Xhtml_ol_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_ol_type := range backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr {
		backRepoXhtml_ol_type.CommitPhaseTwoInstance(backRepo, idx, xhtml_ol_type)
	}

	return
}

// BackRepoXhtml_ol_type.CommitPhaseTwoInstance commits {{structname }} of models.Xhtml_ol_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, xhtml_ol_type *models.Xhtml_ol_type) (Error error) {

	// fetch matching xhtml_ol_typeDB
	if xhtml_ol_typeDB, ok := backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB[idx]; ok {

		xhtml_ol_typeDB.CopyBasicFieldsFromXhtml_ol_type(xhtml_ol_type)

		// insertion point for translating pointers encodings into actual pointers
		query := backRepoXhtml_ol_type.db.Save(&xhtml_ol_typeDB)
		if query.Error != nil {
			log.Fatalln(query.Error)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown Xhtml_ol_type intance %s", xhtml_ol_type.Name))
		return err
	}

	return
}

// BackRepoXhtml_ol_type.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CheckoutPhaseOne() (Error error) {

	xhtml_ol_typeDBArray := make([]Xhtml_ol_typeDB, 0)
	query := backRepoXhtml_ol_type.db.Find(&xhtml_ol_typeDBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	xhtml_ol_typeInstancesToBeRemovedFromTheStage := make(map[*models.Xhtml_ol_type]any)
	for key, value := range backRepoXhtml_ol_type.stage.Xhtml_ol_types {
		xhtml_ol_typeInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, xhtml_ol_typeDB := range xhtml_ol_typeDBArray {
		backRepoXhtml_ol_type.CheckoutPhaseOneInstance(&xhtml_ol_typeDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		xhtml_ol_type, ok := backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr[xhtml_ol_typeDB.ID]
		if ok {
			delete(xhtml_ol_typeInstancesToBeRemovedFromTheStage, xhtml_ol_type)
		}
	}

	// remove from stage and back repo's 3 maps all xhtml_ol_types that are not in the checkout
	for xhtml_ol_type := range xhtml_ol_typeInstancesToBeRemovedFromTheStage {
		xhtml_ol_type.Unstage(backRepoXhtml_ol_type.GetStage())

		// remove instance from the back repo 3 maps
		xhtml_ol_typeID := backRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID[xhtml_ol_type]
		delete(backRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID, xhtml_ol_type)
		delete(backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB, xhtml_ol_typeID)
		delete(backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr, xhtml_ol_typeID)
	}

	return
}

// CheckoutPhaseOneInstance takes a xhtml_ol_typeDB that has been found in the DB, updates the backRepo and stages the
// models version of the xhtml_ol_typeDB
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CheckoutPhaseOneInstance(xhtml_ol_typeDB *Xhtml_ol_typeDB) (Error error) {

	xhtml_ol_type, ok := backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr[xhtml_ol_typeDB.ID]
	if !ok {
		xhtml_ol_type = new(models.Xhtml_ol_type)

		backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr[xhtml_ol_typeDB.ID] = xhtml_ol_type
		backRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID[xhtml_ol_type] = xhtml_ol_typeDB.ID

		// append model store with the new element
		xhtml_ol_type.Name = xhtml_ol_typeDB.Name_Data.String
		xhtml_ol_type.Stage(backRepoXhtml_ol_type.GetStage())
	}
	xhtml_ol_typeDB.CopyBasicFieldsToXhtml_ol_type(xhtml_ol_type)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	xhtml_ol_type.Stage(backRepoXhtml_ol_type.GetStage())

	// preserve pointer to xhtml_ol_typeDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB)[xhtml_ol_typeDB hold variable pointers
	xhtml_ol_typeDB_Data := *xhtml_ol_typeDB
	preservedPtrToXhtml_ol_type := &xhtml_ol_typeDB_Data
	backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB[xhtml_ol_typeDB.ID] = preservedPtrToXhtml_ol_type

	return
}

// BackRepoXhtml_ol_type.CheckoutPhaseTwo Checkouts all staged instances of Xhtml_ol_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, xhtml_ol_typeDB := range backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB {
		backRepoXhtml_ol_type.CheckoutPhaseTwoInstance(backRepo, xhtml_ol_typeDB)
	}
	return
}

// BackRepoXhtml_ol_type.CheckoutPhaseTwoInstance Checkouts staged instances of Xhtml_ol_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, xhtml_ol_typeDB *Xhtml_ol_typeDB) (Error error) {

	xhtml_ol_type := backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr[xhtml_ol_typeDB.ID]

	xhtml_ol_typeDB.DecodePointers(backRepo, xhtml_ol_type)

	return
}

func (xhtml_ol_typeDB *Xhtml_ol_typeDB) DecodePointers(backRepo *BackRepoStruct, xhtml_ol_type *models.Xhtml_ol_type) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitXhtml_ol_type allows commit of a single xhtml_ol_type (if already staged)
func (backRepo *BackRepoStruct) CommitXhtml_ol_type(xhtml_ol_type *models.Xhtml_ol_type) {
	backRepo.BackRepoXhtml_ol_type.CommitPhaseOneInstance(xhtml_ol_type)
	if id, ok := backRepo.BackRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID[xhtml_ol_type]; ok {
		backRepo.BackRepoXhtml_ol_type.CommitPhaseTwoInstance(backRepo, id, xhtml_ol_type)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitXhtml_ol_type allows checkout of a single xhtml_ol_type (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutXhtml_ol_type(xhtml_ol_type *models.Xhtml_ol_type) {
	// check if the xhtml_ol_type is staged
	if _, ok := backRepo.BackRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID[xhtml_ol_type]; ok {

		if id, ok := backRepo.BackRepoXhtml_ol_type.Map_Xhtml_ol_typePtr_Xhtml_ol_typeDBID[xhtml_ol_type]; ok {
			var xhtml_ol_typeDB Xhtml_ol_typeDB
			xhtml_ol_typeDB.ID = id

			if err := backRepo.BackRepoXhtml_ol_type.db.First(&xhtml_ol_typeDB, id).Error; err != nil {
				log.Fatalln("CheckoutXhtml_ol_type : Problem with getting object with id:", id)
			}
			backRepo.BackRepoXhtml_ol_type.CheckoutPhaseOneInstance(&xhtml_ol_typeDB)
			backRepo.BackRepoXhtml_ol_type.CheckoutPhaseTwoInstance(backRepo, &xhtml_ol_typeDB)
		}
	}
}

// CopyBasicFieldsFromXhtml_ol_type
func (xhtml_ol_typeDB *Xhtml_ol_typeDB) CopyBasicFieldsFromXhtml_ol_type(xhtml_ol_type *models.Xhtml_ol_type) {
	// insertion point for fields commit

	xhtml_ol_typeDB.Name_Data.String = xhtml_ol_type.Name
	xhtml_ol_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_ol_type_WOP
func (xhtml_ol_typeDB *Xhtml_ol_typeDB) CopyBasicFieldsFromXhtml_ol_type_WOP(xhtml_ol_type *models.Xhtml_ol_type_WOP) {
	// insertion point for fields commit

	xhtml_ol_typeDB.Name_Data.String = xhtml_ol_type.Name
	xhtml_ol_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsFromXhtml_ol_typeWOP
func (xhtml_ol_typeDB *Xhtml_ol_typeDB) CopyBasicFieldsFromXhtml_ol_typeWOP(xhtml_ol_type *Xhtml_ol_typeWOP) {
	// insertion point for fields commit

	xhtml_ol_typeDB.Name_Data.String = xhtml_ol_type.Name
	xhtml_ol_typeDB.Name_Data.Valid = true
}

// CopyBasicFieldsToXhtml_ol_type
func (xhtml_ol_typeDB *Xhtml_ol_typeDB) CopyBasicFieldsToXhtml_ol_type(xhtml_ol_type *models.Xhtml_ol_type) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_ol_type.Name = xhtml_ol_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_ol_type_WOP
func (xhtml_ol_typeDB *Xhtml_ol_typeDB) CopyBasicFieldsToXhtml_ol_type_WOP(xhtml_ol_type *models.Xhtml_ol_type_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_ol_type.Name = xhtml_ol_typeDB.Name_Data.String
}

// CopyBasicFieldsToXhtml_ol_typeWOP
func (xhtml_ol_typeDB *Xhtml_ol_typeDB) CopyBasicFieldsToXhtml_ol_typeWOP(xhtml_ol_type *Xhtml_ol_typeWOP) {
	xhtml_ol_type.ID = int(xhtml_ol_typeDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	xhtml_ol_type.Name = xhtml_ol_typeDB.Name_Data.String
}

// Backup generates a json file from a slice of all Xhtml_ol_typeDB instances in the backrepo
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "Xhtml_ol_typeDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_ol_typeDB, 0)
	for _, xhtml_ol_typeDB := range backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB {
		forBackup = append(forBackup, xhtml_ol_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json Xhtml_ol_type ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json Xhtml_ol_type file", err.Error())
	}
}

// Backup generates a json file from a slice of all Xhtml_ol_typeDB instances in the backrepo
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Xhtml_ol_typeDB, 0)
	for _, xhtml_ol_typeDB := range backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB {
		forBackup = append(forBackup, xhtml_ol_typeDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Xhtml_ol_type")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Xhtml_ol_type_Fields, -1)
	for _, xhtml_ol_typeDB := range forBackup {

		var xhtml_ol_typeWOP Xhtml_ol_typeWOP
		xhtml_ol_typeDB.CopyBasicFieldsToXhtml_ol_typeWOP(&xhtml_ol_typeWOP)

		row := sh.AddRow()
		row.WriteStruct(&xhtml_ol_typeWOP, -1)
	}
}

// RestoreXL from the "Xhtml_ol_type" sheet all Xhtml_ol_typeDB instances
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoXhtml_ol_typeid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Xhtml_ol_type"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoXhtml_ol_type.rowVisitorXhtml_ol_type)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) rowVisitorXhtml_ol_type(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var xhtml_ol_typeWOP Xhtml_ol_typeWOP
		row.ReadStruct(&xhtml_ol_typeWOP)

		// add the unmarshalled struct to the stage
		xhtml_ol_typeDB := new(Xhtml_ol_typeDB)
		xhtml_ol_typeDB.CopyBasicFieldsFromXhtml_ol_typeWOP(&xhtml_ol_typeWOP)

		xhtml_ol_typeDB_ID_atBackupTime := xhtml_ol_typeDB.ID
		xhtml_ol_typeDB.ID = 0
		query := backRepoXhtml_ol_type.db.Create(xhtml_ol_typeDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB[xhtml_ol_typeDB.ID] = xhtml_ol_typeDB
		BackRepoXhtml_ol_typeid_atBckpTime_newID[xhtml_ol_typeDB_ID_atBackupTime] = xhtml_ol_typeDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "Xhtml_ol_typeDB.json" in dirPath that stores an array
// of Xhtml_ol_typeDB and stores it in the database
// the map BackRepoXhtml_ol_typeid_atBckpTime_newID is updated accordingly
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoXhtml_ol_typeid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "Xhtml_ol_typeDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json Xhtml_ol_type file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*Xhtml_ol_typeDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB
	for _, xhtml_ol_typeDB := range forRestore {

		xhtml_ol_typeDB_ID_atBackupTime := xhtml_ol_typeDB.ID
		xhtml_ol_typeDB.ID = 0
		query := backRepoXhtml_ol_type.db.Create(xhtml_ol_typeDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB[xhtml_ol_typeDB.ID] = xhtml_ol_typeDB
		BackRepoXhtml_ol_typeid_atBckpTime_newID[xhtml_ol_typeDB_ID_atBackupTime] = xhtml_ol_typeDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json Xhtml_ol_type file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Xhtml_ol_type>id_atBckpTime_newID
// to compute new index
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) RestorePhaseTwo() {

	for _, xhtml_ol_typeDB := range backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB {

		// next line of code is to avert unused variable compilation error
		_ = xhtml_ol_typeDB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		query := backRepoXhtml_ol_type.db.Model(xhtml_ol_typeDB).Updates(*xhtml_ol_typeDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
	}

}

// BackRepoXhtml_ol_type.ResetReversePointers commits all staged instances of Xhtml_ol_type to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, xhtml_ol_type := range backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typePtr {
		backRepoXhtml_ol_type.ResetReversePointersInstance(backRepo, idx, xhtml_ol_type)
	}

	return
}

func (backRepoXhtml_ol_type *BackRepoXhtml_ol_typeStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, xhtml_ol_type *models.Xhtml_ol_type) (Error error) {

	// fetch matching xhtml_ol_typeDB
	if xhtml_ol_typeDB, ok := backRepoXhtml_ol_type.Map_Xhtml_ol_typeDBID_Xhtml_ol_typeDB[idx]; ok {
		_ = xhtml_ol_typeDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoXhtml_ol_typeid_atBckpTime_newID map[uint]uint
